import type { JsSeedTag } from "./types";

const PART = "Dữ liệu";

// PHẦN 3 — Dữ liệu: mảng cơ bản, biến đổi mảng (forEach/map/filter/reduce/find/sort),
// object, JSON. Bậc 3 hầu hết dùng run requirement (returns/logs) chạy thật trong Web Worker.
// Mẹo: worker chỉ trả SCALAR → hàm trả mảng thì call tự rút gọn (vd .join('-')), equals ở server.
export const PART3_DU_LIEU: JsSeedTag[] = [
  // ===== CHƯƠNG 9: MẢNG CƠ BẢN =====
  {
    name: "tạo & truy cập mảng",
    topic: "Mảng cơ bản",
    part: PART,
    description: "Mảng [] và truy cập phần tử theo chỉ số (bắt đầu từ 0)",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn chuẩn bị một giỏ hàng chưa có món nào. Tạo một mảng rỗng viết thế nào?",
        options: ["const a = []", "const a = {}", "const a = ()", "const a = new Array{}"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: 'Cho const a = ["x", "y", "z"]; thì a[0] là gì?',
        options: ['"x"', '"y"', '"z"', "0"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn biết giỏ hàng a đang có bao nhiêu món. Lấy số phần tử của mảng dùng gì?",
        options: ["a.length", "a.size()", "length(a)", "a.count"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: 'Cho a = ["x", "y", "z"]; truy cập phần tử CUỐI dùng cách nào?',
        options: ["a[a.length - 1]", "a[a.length]", "a.last", "a[-1] (luôn được)"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Truy cập chỉ số vượt quá mảng (vd a[99] khi mảng có 3 phần tử) trả về gì?",
        options: ["undefined", "0", "null", "Báo lỗi dừng chương trình"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Mảng trong JS có thể chứa các kiểu khác nhau không?",
        options: [
          'Có: [1, "hai", true] hợp lệ',
          "Không, chỉ một kiểu",
          "Chỉ chứa số",
          "Chỉ chứa chuỗi",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm phanTuDau(arr) trả về phần tử ĐẦU TIÊN của mảng. Ví dụ phanTuDau([10, 20]) = 10.",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "phanTuDau", message: "Tên hàm là phanTuDau" },
          { type: "contains", text: "[0]", message: "Truy cập phần tử chỉ số [0]" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "phanTuDau([10, 20])", equals: 10, message: "phanTuDau([10,20]) phải trả 10" },
          { type: "returns", call: 'phanTuDau(["a", "b"])', equals: "a", message: 'phanTuDau(["a","b"]) phải trả "a"' },
        ],
        starterCode: "function phanTuDau(arr) {\n  // return arr[0]\n}\n",
      },
    ],
  },
  {
    name: "thêm/xóa cuối mảng",
    topic: "Mảng cơ bản",
    part: PART,
    description: "push thêm cuối, pop lấy & xóa cuối",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Người dùng bấm 'Thêm vào giỏ', cần đưa món mới vào CUỐI mảng giỏ hàng. Dùng method nào?",
        options: ["arr.push(x)", "arr.add(x)", "arr.append(x)", "arr.last(x)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn lấy ra và bỏ luôn món vừa thêm (ở cuối) khỏi giỏ hàng. Dùng method nào?",
        options: ["arr.pop()", "arr.removeLast()", "arr.shift()", "arr.delete()"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "arr.push(x) trả về gì?",
        options: ["Độ dài MỚI của mảng", "Phần tử vừa thêm", "Mảng cũ", "undefined"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "push và pop có làm THAY ĐỔI mảng gốc không?",
        options: [
          "Có — chúng sửa mảng tại chỗ (mutate)",
          "Không, trả mảng mới",
          "Chỉ push mới sửa",
          "Chỉ pop mới sửa",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "arr.pop() trên mảng RỖNG trả về gì?",
        options: ["undefined", "null", "0", "Báo lỗi"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Dùng push trên mảng khai báo bằng const có được không?",
        options: [
          "Được — const cấm GÁN LẠI biến, nhưng vẫn sửa nội dung mảng",
          "Không, const cấm mọi thay đổi",
          "Chỉ được với let",
          "Báo lỗi runtime",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm themCuoi(arr, x): push x vào cuối arr rồi trả về độ dài mới (arr.length). Ví dụ themCuoi([1, 2], 9) = 3.",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "themCuoi", message: "Tên hàm là themCuoi" },
          { type: "contains", text: ".push", message: "Dùng .push()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "themCuoi([1, 2], 9)", equals: 3, message: "themCuoi([1,2],9) phải trả 3" },
          { type: "returns", call: "themCuoi([], 5)", equals: 1, message: "themCuoi([],5) phải trả 1" },
        ],
        starterCode: "function themCuoi(arr, x) {\n  // arr.push(x) rồi return arr.length\n}\n",
      },
    ],
  },
  {
    name: "thêm/xóa đầu mảng",
    topic: "Mảng cơ bản",
    part: PART,
    description: "unshift thêm đầu, shift lấy & xóa đầu",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn chèn thông báo mới nhất lên ĐẦU danh sách. Thêm một phần tử vào đầu mảng dùng method nào?",
        options: ["arr.unshift(x)", "arr.push(x)", "arr.shift(x)", "arr.first(x)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Hàng đợi: xử lý xong người ĐẦU tiên thì lấy ra và bỏ khỏi mảng. Dùng method nào?",
        options: ["arr.shift()", "arr.pop()", "arr.unshift()", "arr.removeFirst()"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Sau khi shift, các phần tử còn lại thế nào?",
        options: [
          "Dồn lên — chỉ số mỗi phần tử giảm 1",
          "Giữ nguyên chỉ số",
          "Bị đảo ngược",
          "Bị xóa hết",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "So với push/pop, shift/unshift thường chậm hơn vì sao?",
        options: [
          "Phải dịch chỉ số mọi phần tử còn lại",
          "Vì tên dài hơn",
          "Vì trả mảng mới",
          "Chúng không chậm hơn",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "arr.unshift(x) trả về gì?",
        options: ["Độ dài MỚI của mảng", "Phần tử vừa thêm", "undefined", "Mảng cũ"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Tóm tắt: cặp method nào thao tác ở ĐẦU mảng?",
        options: ["shift / unshift", "push / pop", "slice / splice", "map / filter"],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm themDau(arr, x): unshift x vào đầu arr rồi trả về phần tử đầu (arr[0]). Ví dụ themDau([2, 3], 1) = 1.",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "themDau", message: "Tên hàm là themDau" },
          { type: "contains", text: ".unshift", message: "Dùng .unshift()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "themDau([2, 3], 1)", equals: 1, message: "themDau([2,3],1) phải trả 1" },
          { type: "returns", call: "themDau([9], 5)", equals: 5, message: "themDau([9],5) phải trả 5" },
        ],
        starterCode: "function themDau(arr, x) {\n  // arr.unshift(x) rồi return arr[0]\n}\n",
      },
    ],
  },
  {
    name: "tìm trong mảng",
    topic: "Mảng cơ bản",
    part: PART,
    description: "Kiểm tra tồn tại bằng includes, vị trí bằng indexOf",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Kiểm tra danh sách yêu thích có chứa sản phẩm x chưa (trả true/false). Dùng gì?",
        options: ["arr.includes(x)", "arr.has(x)", "arr.contains(x)", "arr.exists(x)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn biết sản phẩm x đang nằm ở VỊ TRÍ nào (chỉ số) trong mảng. Dùng gì?",
        options: ["arr.indexOf(x)", "arr.find(x)", "arr.position(x)", "arr.key(x)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "arr.indexOf(x) trả về gì khi KHÔNG tìm thấy x?",
        options: ["-1", "0", "undefined", "null"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "includes so sánh giá trị bằng kiểu nào?",
        options: ["=== (chặt)", "== (lỏng)", "chỉ so chuỗi", "ngẫu nhiên"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Viết điều kiện 'nếu mảng KHÔNG chứa x' thế nào?",
        options: ["if (!arr.includes(x))", "if (arr.includes(x) = false)", "if (arr.notIncludes(x))", "if (arr.includes(x) == -1)"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác nhau giữa includes và indexOf khi chỉ cần biết CÓ hay KHÔNG?",
        options: [
          "includes rõ nghĩa hơn (trả boolean); indexOf trả số nên phải so với -1",
          "Hoàn toàn giống nhau",
          "indexOf trả boolean",
          "includes trả chỉ số",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: 'Viết hàm coMau(arr) trả về true nếu arr chứa "đỏ", ngược lại false (dùng includes). Ví dụ coMau(["đỏ", "xanh"]) = true.',
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "coMau", message: "Tên hàm là coMau" },
          { type: "contains", text: ".includes", message: "Dùng .includes()" },
          { type: "contains", text: "đỏ", message: 'Kiểm tra giá trị "đỏ"' },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: 'coMau(["đỏ", "xanh"])', equals: true, message: 'coMau(["đỏ","xanh"]) phải trả true' },
          { type: "returns", call: 'coMau(["xanh"])', equals: false, message: 'coMau(["xanh"]) phải trả false' },
        ],
        starterCode: 'function coMau(arr) {\n  // return arr.includes("đỏ")\n}\n',
      },
    ],
  },

  // ===== CHƯƠNG 10: BIẾN ĐỔI MẢNG =====
  {
    name: "forEach",
    topic: "Biến đổi mảng",
    part: PART,
    description: "Duyệt qua từng phần tử để xử lý (không trả mảng mới)",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Duyệt từng phần tử mảng để xử lý (vd in ra) dùng method nào?",
        options: ["arr.forEach(x => ...)", "arr.loop(x => ...)", "arr.each(x => ...)", "forEach(arr)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Hàm callback của forEach nhận tham số đầu tiên là gì?",
        options: ["Giá trị phần tử hiện tại", "Chỉ số", "Cả mảng", "Độ dài"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "forEach trả về gì?",
        options: ["undefined (dùng để chạy tác dụng phụ)", "Mảng mới", "Số phần tử", "Phần tử cuối"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Callback của forEach có thể nhận thêm tham số thứ hai là gì?",
        options: ["Chỉ số (index)", "Độ dài", "Phần tử kế tiếp", "Tên mảng"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khi nào dùng forEach thay vì map?",
        options: [
          "Khi chỉ cần CHẠY việc gì đó với mỗi phần tử, KHÔNG cần mảng kết quả",
          "Khi cần mảng mới biến đổi",
          "Khi cần lọc phần tử",
          "Khi cần tính tổng",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "break có dừng được vòng forEach không?",
        options: [
          "Không — forEach không hỗ trợ break, muốn dừng sớm hãy dùng for/for...of",
          "Có, như vòng for",
          "Có, nhưng phải return",
          "Có, dùng continue",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm inDanhSach(arr) dùng forEach để console.log từng phần tử (mỗi phần tử một dòng).",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "inDanhSach", message: "Tên hàm là inDanhSach" },
          { type: "construct", construct: "forEach", message: "Dùng .forEach()" },
          { type: "contains", text: "console.log", message: "In bằng console.log" },
          { type: "logs", call: 'inDanhSach(["a", "b"])', equals: "a\nb", message: 'inDanhSach(["a","b"]) phải in "a" rồi "b" mỗi dòng' },
        ],
        starterCode: "function inDanhSach(arr) {\n  // arr.forEach(x => console.log(x))\n}\n",
      },
    ],
  },
  {
    name: "map",
    topic: "Biến đổi mảng",
    part: PART,
    description: "Tạo MẢNG MỚI bằng cách biến đổi mỗi phần tử",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Có mảng giá gốc, muốn tạo mảng MỚI giá đã giảm 10% cho từng món. Dùng method nào?",
        options: ["arr.map(x => ...)", "arr.forEach(x => ...)", "arr.change(x => ...)", "arr.transform(x => ...)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Chạy arr.map(...) xong, ta nhận lại được gì?",
        options: ["Một MẢNG MỚI cùng độ dài", "undefined", "Một số", "Mảng gốc đã sửa"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "[1, 2, 3].map(x => x * 10) cho kết quả gì?",
        options: ["[10, 20, 30]", "[1, 2, 3]", "60", "[1, 20, 300]"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "map có làm thay đổi mảng gốc không?",
        options: ["Không — trả mảng mới, mảng gốc giữ nguyên", "Có, sửa tại chỗ", "Tùy callback", "Có, xóa mảng gốc"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Mảng kết quả của map có độ dài thế nào so với mảng gốc?",
        options: ["Bằng nhau", "Luôn ngắn hơn", "Luôn dài hơn", "Bằng 1"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: 'users.map(u => u.ten) làm gì?',
        options: [
          "Trích mảng các tên từ mảng object users",
          "Đếm số user",
          "Lọc user có tên",
          "Sửa tên mỗi user",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm nhanDoi(arr) dùng .map trả về MẢNG MỚI mỗi phần tử gấp đôi. Ví dụ nhanDoi([1, 2, 3]) = [2, 4, 6].",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "nhanDoi", message: "Tên hàm là nhanDoi" },
          { type: "construct", construct: "map", message: "Dùng .map()" },
          { type: "contains", text: "return", message: "Dùng return để trả mảng" },
          { type: "returns", call: "nhanDoi([1, 2, 3]).join('-')", equals: "2-4-6", message: "nhanDoi([1,2,3]) phải là [2,4,6]" },
          { type: "returns", call: "nhanDoi([5]).join('-')", equals: "10", message: "nhanDoi([5]) phải là [10]" },
        ],
        starterCode: "function nhanDoi(arr) {\n  // return arr.map(x => x * 2)\n}\n",
      },
    ],
  },
  {
    name: "filter",
    topic: "Biến đổi mảng",
    part: PART,
    description: "Lọc ra MẢNG MỚI gồm các phần tử thỏa điều kiện",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Từ danh sách sản phẩm, muốn lấy MẢNG MỚI chỉ gồm món còn hàng. Dùng method nào?",
        options: ["arr.filter(x => điều_kiện)", "arr.map(x => điều_kiện)", "arr.select(x => ...)", "arr.where(x => ...)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Callback của filter cần trả về gì để GIỮ phần tử?",
        options: ["true (giá trị truthy)", "phần tử", "số", "undefined"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "[1, 2, 3, 4].filter(x => x > 2) cho kết quả?",
        options: ["[3, 4]", "[1, 2]", "[1, 2, 3, 4]", "2"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Mảng kết quả của filter có độ dài thế nào?",
        options: [
          "Từ 0 đến bằng độ dài gốc (tùy số phần tử thỏa)",
          "Luôn bằng gốc",
          "Luôn bằng 1",
          "Luôn dài hơn gốc",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Lọc số chẵn từ mảng số viết callback thế nào?",
        options: ["x => x % 2 === 0", "x => x / 2", "x => x % 2 === 1", "x => x > 0"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác biệt cốt lõi giữa map và filter?",
        options: [
          "map BIẾN ĐỔI mỗi phần tử (giữ số lượng); filter CHỌN LỌC phần tử (có thể bớt)",
          "Giống hệt nhau",
          "filter biến đổi, map lọc",
          "Cả hai đều sửa mảng gốc",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm soChan(arr) dùng .filter trả về mảng chỉ gồm số chẵn. Ví dụ soChan([1, 2, 3, 4]) = [2, 4].",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "soChan", message: "Tên hàm là soChan" },
          { type: "construct", construct: "filter", message: "Dùng .filter()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "soChan([1, 2, 3, 4, 5, 6]).join('-')", equals: "2-4-6", message: "soChan(1..6) phải là [2,4,6]" },
          { type: "returns", call: "soChan([1, 3, 5]).join('-')", equals: "", message: "soChan([1,3,5]) phải là mảng rỗng" },
        ],
        starterCode: "function soChan(arr) {\n  // return arr.filter(x => x % 2 === 0)\n}\n",
      },
    ],
  },
  {
    name: "reduce",
    topic: "Biến đổi mảng",
    part: PART,
    description: "Gộp cả mảng về MỘT giá trị (tổng, tích, ...)",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Cộng tổng tiền của mọi món trong giỏ về MỘT con số. Gộp cả mảng thành một giá trị dùng method nào?",
        options: ["arr.reduce((tong, x) => tong + x, 0)", "arr.sum()", "arr.total()", "arr.merge()"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Tham số thứ hai của reduce (vd số 0) là gì?",
        options: ["Giá trị khởi tạo của bộ tích lũy", "Chỉ số bắt đầu", "Số lần lặp", "Phần tử cuối"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "[1, 2, 3].reduce((a, b) => a + b, 0) cho kết quả?",
        options: ["6", "0", "[1, 2, 3]", "123"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Callback reduce nhận hai tham số chính là gì?",
        options: [
          "Bộ tích lũy (accumulator) và phần tử hiện tại",
          "Chỉ số và độ dài",
          "Mảng cũ và mảng mới",
          "Hai phần tử kề nhau",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Quên truyền giá trị khởi tạo cho reduce có rủi ro gì?",
        options: [
          "Phần tử đầu được dùng làm khởi tạo — dễ sai và lỗi với mảng rỗng",
          "Không có rủi ro",
          "Luôn trả 0",
          "Báo lỗi cú pháp",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "reduce có thể tạo ra kết quả kiểu gì?",
        options: [
          "Bất kỳ: số, chuỗi, cả object/mảng tùy cách gộp",
          "Chỉ số",
          "Chỉ boolean",
          "Chỉ mảng",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm tongMang(arr) dùng .reduce trả về tổng các số. Ví dụ tongMang([1, 2, 3, 4]) = 10.",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "tongMang", message: "Tên hàm là tongMang" },
          { type: "construct", construct: "reduce", message: "Dùng .reduce()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "tongMang([1, 2, 3, 4])", equals: 10, message: "tongMang([1,2,3,4]) phải trả 10" },
          { type: "returns", call: "tongMang([5])", equals: 5, message: "tongMang([5]) phải trả 5" },
        ],
        starterCode: "function tongMang(arr) {\n  // return arr.reduce((tong, x) => tong + x, 0)\n}\n",
      },
    ],
  },
  {
    name: "find",
    topic: "Biến đổi mảng",
    part: PART,
    description: "Lấy phần tử ĐẦU TIÊN thỏa điều kiện",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn lấy người dùng ĐẦU TIÊN có tuoi > 18 trong danh sách. Dùng method nào?",
        options: ["arr.find(x => điều_kiện)", "arr.filter(x => ...)", "arr.search(x => ...)", "arr.get(x => ...)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "find trả về gì khi KHÔNG có phần tử nào thỏa?",
        options: ["undefined", "-1", "null", "[]"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Khác nhau giữa find và filter?",
        options: [
          "find trả MỘT phần tử (đầu tiên thỏa); filter trả MẢNG mọi phần tử thỏa",
          "Giống hệt nhau",
          "find trả mảng",
          "filter trả một phần tử",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Muốn lấy CHỈ SỐ của phần tử đầu tiên thỏa điều kiện dùng gì?",
        options: ["arr.findIndex(x => ...)", "arr.find(x => ...)", "arr.indexOf(x => ...)", "arr.position(x => ...)"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "find dừng duyệt khi nào?",
        options: [
          "Ngay khi gặp phần tử đầu tiên thỏa điều kiện",
          "Sau khi duyệt hết mảng",
          "Không bao giờ dừng",
          "Khi gặp undefined",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "find hợp dùng nhất trong tình huống nào?",
        options: [
          "Tìm một object theo id trong mảng object",
          "Tính tổng",
          "Biến đổi mọi phần tử",
          "Sắp xếp",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm timLon(arr) dùng .find trả về phần tử ĐẦU TIÊN lớn hơn 10. Ví dụ timLon([5, 8, 12, 20]) = 12.",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "timLon", message: "Tên hàm là timLon" },
          { type: "construct", construct: "find", message: "Dùng .find()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "timLon([5, 8, 12, 20])", equals: 12, message: "timLon([5,8,12,20]) phải trả 12" },
          { type: "returns", call: "timLon([1, 2, 30])", equals: 30, message: "timLon([1,2,30]) phải trả 30" },
        ],
        starterCode: "function timLon(arr) {\n  // return arr.find(x => x > 10)\n}\n",
      },
    ],
  },
  {
    name: "sort",
    topic: "Biến đổi mảng",
    part: PART,
    description: "Sắp xếp mảng — cẩn thận với so sánh mặc định",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn sắp xếp danh sách điểm từ thấp đến cao để hiển thị. Sắp xếp mảng dùng method nào?",
        options: ["arr.sort()", "arr.order()", "arr.arrange()", "sort(arr)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "sort có làm thay đổi mảng gốc không?",
        options: ["Có — sắp xếp tại chỗ (mutate)", "Không, trả mảng mới", "Tùy trình duyệt", "Chỉ với số"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Sắp xếp số TĂNG dần cần truyền hàm so sánh nào?",
        options: ["(a, b) => a - b", "(a, b) => a + b", "(a, b) => b - a", "() => true"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "[10, 2, 1].sort() (KHÔNG có hàm so sánh) cho kết quả gì?",
        options: [
          "[1, 10, 2] — vì so sánh theo CHUỖI mặc định",
          "[1, 2, 10]",
          "[10, 2, 1]",
          "[2, 1, 10]",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Sắp xếp số GIẢM dần dùng hàm so sánh nào?",
        options: ["(a, b) => b - a", "(a, b) => a - b", "(a, b) => a + b", "(a, b) => a > b"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Muốn KHÔNG làm hỏng mảng gốc khi sort thì làm sao?",
        options: [
          "Sao chép trước: [...arr].sort(...)",
          "Không thể tránh",
          "Dùng arr.sortNew()",
          "Dùng map thay sort",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm sapXep(arr) dùng .sort trả về mảng số sắp xếp TĂNG dần. Ví dụ sapXep([10, 2, 1]) = [1, 2, 10].",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "sapXep", message: "Tên hàm là sapXep" },
          { type: "contains", text: ".sort", message: "Dùng .sort()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "sapXep([10, 2, 1]).join('-')", equals: "1-2-10", message: "sapXep([10,2,1]) phải là [1,2,10]" },
          { type: "returns", call: "sapXep([3, 1, 2]).join('-')", equals: "1-2-3", message: "sapXep([3,1,2]) phải là [1,2,3]" },
        ],
        starterCode: "function sapXep(arr) {\n  // return arr.sort((a, b) => a - b)\n}\n",
      },
    ],
  },

  // ===== CHƯƠNG 11: OBJECT =====
  {
    name: "tạo & truy cập object",
    topic: "Object",
    part: PART,
    description: "Object {} gom dữ liệu theo cặp khóa: giá trị",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Tạo một object mô tả người dùng viết thế nào?",
        options: [
          'const u = { ten: "An", tuoi: 20 }',
          'const u = ["An", 20]',
          'const u = (ten: "An")',
          'const u = <ten="An">',
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: 'Cho u = { ten: "An" }; truy cập tên dùng cách nào?',
        options: ['u.ten hoặc u["ten"]', "u(ten)", "u->ten", "u::ten"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Phần bên trái dấu : trong object gọi là gì?",
        options: ["Khóa (key/property)", "Giá trị", "Chỉ số", "Hàm"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Truy cập một khóa KHÔNG tồn tại trên object trả về gì?",
        options: ["undefined", "null", "Báo lỗi", "0"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khi nào BẮT BUỘC dùng cú pháp ngoặc vuông obj[\"key\"]?",
        options: [
          "Khi tên khóa nằm trong biến hoặc có ký tự đặc biệt/khoảng trắng",
          "Luôn luôn bắt buộc",
          "Không bao giờ cần",
          "Chỉ với số",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác biệt cốt lõi giữa object và mảng?",
        options: [
          "Object truy cập bằng KHÓA có tên; mảng truy cập bằng CHỈ SỐ thứ tự",
          "Giống hệt nhau",
          "Object chỉ chứa số",
          "Mảng có khóa tên",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: 'Viết hàm layTen(nguoi) trả về thuộc tính ten của object nguoi. Ví dụ layTen({ ten: "An" }) = "An".',
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "layTen", message: "Tên hàm là layTen" },
          { type: "contains", text: ".ten", message: "Truy cập nguoi.ten" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: 'layTen({ ten: "An" })', equals: "An", message: 'layTen({ten:"An"}) phải trả "An"' },
          { type: "returns", call: 'layTen({ ten: "Bình" })', equals: "Bình", message: 'layTen({ten:"Bình"}) phải trả "Bình"' },
        ],
        starterCode: "function layTen(nguoi) {\n  // return nguoi.ten\n}\n",
      },
    ],
  },
  {
    name: "sửa thuộc tính object",
    topic: "Object",
    part: PART,
    description: "Thêm, sửa, xóa cặp khóa: giá trị của object",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: 'Gán u.tuoi = 21 trên object u làm gì?',
        options: [
          "Đặt/cập nhật thuộc tính tuoi thành 21",
          "Tạo biến tuoi",
          "Xóa thuộc tính tuoi",
          "Báo lỗi",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Thêm một thuộc tính MỚI vào object đã có viết thế nào?",
        options: ['u.email = "a@b.com"', 'u.add("email")', 'u.push("email")', 'u + "email"'],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Xóa một thuộc tính khỏi object dùng từ khóa nào?",
        options: ["delete u.tuoi", "remove u.tuoi", "u.tuoi = null (luôn xóa)", "drop u.tuoi"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "const u = {}; sau đó u.ten = \"An\"; có hợp lệ không?",
        options: [
          "Hợp lệ — const cấm gán lại u, không cấm sửa nội dung object",
          "Lỗi vì u là const",
          "Chỉ với let",
          "Phải khai báo ten trước",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Kiểm tra object u có khóa 'email' không dùng cách nào?",
        options: ['"email" in u', "u.has(email)", "u.contains(email)", "email in u (không nháy)"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Hai biến cùng trỏ tới MỘT object, sửa qua biến này thì biến kia thế nào?",
        options: [
          "Cũng thấy thay đổi — object truyền theo tham chiếu",
          "Không ảnh hưởng",
          "Tự sao chép",
          "Báo lỗi",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm tangTuoi(nguoi): tăng nguoi.tuoi thêm 1 rồi trả về nguoi.tuoi. Ví dụ tangTuoi({ tuoi: 20 }) = 21.",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "tangTuoi", message: "Tên hàm là tangTuoi" },
          { type: "contains", text: ".tuoi", message: "Truy cập nguoi.tuoi" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "tangTuoi({ tuoi: 20 })", equals: 21, message: "tangTuoi({tuoi:20}) phải trả 21" },
          { type: "returns", call: "tangTuoi({ tuoi: 0 })", equals: 1, message: "tangTuoi({tuoi:0}) phải trả 1" },
        ],
        starterCode: "function tangTuoi(nguoi) {\n  // nguoi.tuoi += 1 rồi return nguoi.tuoi\n}\n",
      },
    ],
  },
  {
    name: "Object.keys/values",
    topic: "Object",
    part: PART,
    description: "Lấy danh sách khóa, giá trị, cặp của object",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Lấy MẢNG các khóa của object obj dùng gì?",
        options: ["Object.keys(obj)", "obj.keys()", "keys(obj)", "obj.allKeys"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Lấy MẢNG các giá trị của object dùng gì?",
        options: ["Object.values(obj)", "obj.values()", "values(obj)", "obj.allValues"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Object.entries(obj) trả về gì?",
        options: [
          "Mảng các cặp [khóa, giá trị]",
          "Chỉ các khóa",
          "Chỉ các giá trị",
          "Số thuộc tính",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Đếm số thuộc tính của object dùng cách nào?",
        options: ["Object.keys(obj).length", "obj.length", "obj.size", "count(obj)"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Duyệt mọi cặp khóa-giá trị của object nên kết hợp gì?",
        options: [
          "Object.entries(obj) rồi for...of / forEach",
          "obj.forEach trực tiếp",
          "for (i=0; i<obj.length)",
          "obj.map",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao object không duyệt trực tiếp bằng for...of được?",
        options: [
          "Object không phải iterable; phải qua Object.keys/values/entries",
          "Vì object quá lớn",
          "Vì thiếu .length",
          "Thực ra duyệt trực tiếp được",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: "Viết hàm soThuocTinh(obj) trả về SỐ thuộc tính của obj (dùng Object.keys). Ví dụ soThuocTinh({ a: 1, b: 2 }) = 2.",
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "soThuocTinh", message: "Tên hàm là soThuocTinh" },
          { type: "contains", text: "Object.keys", message: "Dùng Object.keys()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "soThuocTinh({ a: 1, b: 2 })", equals: 2, message: "soThuocTinh({a,b}) phải trả 2" },
          { type: "returns", call: "soThuocTinh({})", equals: 0, message: "soThuocTinh({}) phải trả 0" },
        ],
        starterCode: "function soThuocTinh(obj) {\n  // return Object.keys(obj).length\n}\n",
      },
    ],
  },
  {
    name: "destructuring object",
    topic: "Object",
    part: PART,
    description: "Rút thuộc tính ra biến gọn: const { ten } = nguoi",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Rút thuộc tính ten từ object nguoi ra biến viết thế nào?",
        options: ["const { ten } = nguoi", "const ten = nguoi[ten]", "const (ten) = nguoi", "const ten => nguoi"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Destructuring nhiều thuộc tính một lúc viết thế nào?",
        options: [
          "const { ten, tuoi } = nguoi",
          "const { ten; tuoi } = nguoi",
          "const [ten, tuoi] = nguoi",
          "const ten, tuoi = nguoi",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Tên biến trong destructuring object phải thế nào so với khóa?",
        options: [
          "Trùng tên khóa (hoặc đổi tên bằng : )",
          "Bất kỳ tên nào",
          "Phải viết hoa",
          "Phải có số",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Destructuring khóa không tồn tại cho biến giá trị gì?",
        options: ["undefined", "null", "0", "Báo lỗi"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Đặt giá trị mặc định khi destructuring viết thế nào?",
        options: [
          'const { ten = "khách" } = nguoi',
          'const { ten || "khách" } = nguoi',
          'const { ten ?? "khách" } = nguoi',
          'const { ten: "khách" } = nguoi',
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Lợi ích chính của destructuring là gì?",
        options: [
          "Code gọn, rõ — lấy nhiều thuộc tính mà không lặp tên object",
          "Chạy nhanh hơn nhiều",
          "Tự kiểm tra kiểu",
          "Tạo object mới",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: 'Viết hàm layTen2(nguoi) dùng destructuring (const { ten } = nguoi) rồi trả về ten. Ví dụ layTen2({ ten: "Bình" }) = "Bình".',
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "layTen2", message: "Tên hàm là layTen2" },
          { type: "construct", construct: "destructure", message: "Dùng destructuring { } =" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: 'layTen2({ ten: "Bình" })', equals: "Bình", message: 'layTen2 phải trả "Bình"' },
          { type: "returns", call: 'layTen2({ ten: "An" })', equals: "An", message: 'layTen2 phải trả "An"' },
        ],
        starterCode: "function layTen2(nguoi) {\n  // const { ten } = nguoi;\n  // return ten;\n}\n",
      },
    ],
  },
  {
    name: "spread object",
    topic: "Object",
    part: PART,
    description: "Sao chép & gộp object bằng ... (spread)",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Tạo BẢN SAO của object u dùng cú pháp nào?",
        options: ["const v = { ...u }", "const v = u.copy()", "const v = u", "const v = [...u]"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Gộp hai object a và b thành một viết thế nào?",
        options: ["{ ...a, ...b }", "{ a + b }", "a.merge(b)", "[a, b]"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Toán tử spread cho object dùng ký hiệu gì?",
        options: ["... (ba chấm)", ":: (hai hai chấm)", "** (sao đôi)", "& (và)"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Trong { ...a, ten: \"mới\" } nếu a đã có ten thì sao?",
        options: [
          'Khóa sau ("mới") GHI ĐÈ giá trị từ a',
          "Báo lỗi trùng khóa",
          "Giữ giá trị của a",
          "Bỏ cả hai",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "const v = { ...u } là bản sao kiểu gì?",
        options: [
          "Sao chép NÔNG (shallow) — object lồng bên trong vẫn dùng chung tham chiếu",
          "Sao chép SÂU hoàn toàn",
          "Không sao chép gì",
          "Chỉ sao khóa đầu",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao spread hay dùng để 'cập nhật' state mà không sửa gốc?",
        options: [
          "Tạo object MỚI với vài thay đổi, giữ object cũ bất biến",
          "Vì nó nhanh hơn",
          "Vì nó xóa object cũ",
          "Vì nó tự lưu vào DB",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: 'Viết hàm themEmail(nguoi) dùng spread (...) trả về OBJECT MỚI gồm mọi thuộc tính của nguoi và thêm email = "x@y.com". Ví dụ themEmail({ ten: "An" }).email = "x@y.com".',
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "themEmail", message: "Tên hàm là themEmail" },
          { type: "construct", construct: "spread", message: "Dùng spread (...)" },
          { type: "contains", text: "email", message: "Thêm thuộc tính email" },
          { type: "contains", text: "x@y.com", message: 'Giá trị email = "x@y.com"' },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: 'themEmail({ ten: "An" }).email', equals: "x@y.com", message: 'email phải là "x@y.com"' },
          { type: "returns", call: 'themEmail({ ten: "An" }).ten', equals: "An", message: "phải giữ thuộc tính ten" },
        ],
        starterCode: 'function themEmail(nguoi) {\n  // return { ...nguoi, email: "x@y.com" }\n}\n',
      },
    ],
  },

  // ===== CHƯƠNG 12: JSON =====
  {
    name: "JSON.stringify",
    topic: "JSON",
    part: PART,
    description: "Chuyển object/mảng thành CHUỖI JSON để lưu/gửi",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn lưu object giỏ hàng vào localStorage (chỉ nhận chuỗi). Chuyển object thành chuỗi JSON dùng gì?",
        options: ["JSON.stringify(obj)", "obj.toJSON()", "String(obj)", "JSON.toString(obj)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "JSON dùng để làm gì?",
        options: [
          "Định dạng chuỗi để LƯU/GỬI dữ liệu giữa các hệ thống",
          "Tăng tốc vòng lặp",
          "Vẽ giao diện",
          "Khai báo biến",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: 'JSON.stringify({ a: 1 }) cho kết quả gì?',
        options: ['Chuỗi {"a":1}', "Object { a: 1 }", "Số 1", "Mảng [1]"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khóa trong chuỗi JSON được viết thế nào?",
        options: [
          'Luôn bọc trong nháy KÉP: {"ten":"An"}',
          "Không có nháy",
          "Bọc nháy đơn",
          "Bọc backtick",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "JSON.stringify(obj, null, 2) thêm gì?",
        options: [
          "Thụt lề 2 dấu cách cho dễ đọc",
          "Bỏ khóa null",
          "Giới hạn 2 thuộc tính",
          "Mã hóa dữ liệu",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Giá trị nào thường bị BỎ khi stringify?",
        options: [
          "function và undefined (không hợp lệ trong JSON)",
          "Số",
          "Chuỗi",
          "Mảng",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: 'Viết hàm sangChuoi(obj) trả về chuỗi JSON của obj (dùng JSON.stringify). Ví dụ sangChuoi({ a: 1 }) = {"a":1}.',
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "sangChuoi", message: "Tên hàm là sangChuoi" },
          { type: "contains", text: "JSON.stringify", message: "Dùng JSON.stringify()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: "sangChuoi({ a: 1 })", equals: '{"a":1}', message: 'sangChuoi({a:1}) phải là {"a":1}' },
          { type: "returns", call: "sangChuoi({ x: true })", equals: '{"x":true}', message: 'sangChuoi({x:true}) phải là {"x":true}' },
        ],
        starterCode: "function sangChuoi(obj) {\n  // return JSON.stringify(obj)\n}\n",
      },
    ],
  },
  {
    name: "JSON.parse",
    topic: "JSON",
    part: PART,
    description: "Chuyển chuỗi JSON trở lại object/mảng để dùng",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Đọc lại chuỗi JSON từ localStorage và muốn dùng nó như object. Chuyển chuỗi JSON trở lại object dùng gì?",
        options: ["JSON.parse(chuoi)", "JSON.toObject(chuoi)", "Object(chuoi)", "parse(chuoi)"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: 'JSON.parse(\'{"a":5}\') trả về gì?',
        options: ["Object { a: 5 }", 'Chuỗi {"a":5}', "Số 5", "Mảng [5]"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "stringify và parse có quan hệ gì?",
        options: [
          "Ngược nhau: stringify object→chuỗi, parse chuỗi→object",
          "Giống hệt nhau",
          "Cả hai trả chuỗi",
          "Cả hai trả object",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "JSON.parse nhận chuỗi SAI định dạng thì sao?",
        options: [
          "Ném lỗi (throw) — nên bọc trong try/catch",
          "Trả undefined",
          "Trả chuỗi rỗng",
          "Tự sửa lại",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Dữ liệu nhận từ API (fetch) thường ở dạng gì trước khi dùng?",
        options: [
          "Chuỗi JSON — cần parse thành object (hoặc dùng response.json())",
          "Đã là object sẵn",
          "Là số",
          "Là HTML",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao JSON dùng nháy KÉP mà không phải nháy đơn?",
        options: [
          "Chuẩn JSON quy định nháy kép; nháy đơn làm parse lỗi",
          "Vì nháy kép đẹp hơn",
          "Không quan trọng",
          "Vì nháy đơn dành cho số",
        ],
        correctIndex: 0,
      },
      {
        tier: 3, type: "WRITE_JS",
        prompt: 'Viết hàm doc(chuoi) dùng JSON.parse rồi trả về thuộc tính a. Ví dụ doc(\'{"a":5}\') = 5.',
        requirements: [
          { type: "construct", construct: "function", message: "Dùng function" },
          { type: "contains", text: "doc", message: "Tên hàm là doc" },
          { type: "contains", text: "JSON.parse", message: "Dùng JSON.parse()" },
          { type: "contains", text: "return", message: "Dùng return" },
          { type: "returns", call: `doc('{"a":5}')`, equals: 5, message: 'doc(\'{"a":5}\') phải trả 5' },
          { type: "returns", call: `doc('{"a":42}')`, equals: 42, message: 'doc(\'{"a":42}\') phải trả 42' },
        ],
        starterCode: "function doc(chuoi) {\n  // const obj = JSON.parse(chuoi);\n  // return obj.a;\n}\n",
      },
    ],
  },
];
