import type { CssSeedTag } from "./types";

const PART = "Giao diện";

// PHẦN 2 — Chương 6 (Màu & nền) + Chương 7 (Chữ & font)
export const PART2_CHUONG_6_7: CssSeedTag[] = [
  // ===== CHƯƠNG 6: MÀU & NỀN =====
  {
    name: "color",
    topic: "Màu & nền",
    part: PART,
    description: "Màu chữ của phần tử — kế thừa xuống mọi con",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào đổi MÀU CHỮ của phần tử?",
        options: ["text-color", "color", "font-color", "text-style"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Đoạn cảnh báo cần chữ màu đỏ. Khai báo nào đúng?",
        options: ["color: red;", "background: red;", "text: red;", "font: red;"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "color nhận những dạng giá trị nào?",
        options: [
          "Chỉ tên màu tiếng Anh",
          "Tên màu, mã hex, rgb()/rgba(), hsl() — tất cả các dạng màu hợp lệ",
          "Chỉ mã hex",
          "Chỉ rgb()",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Đặt color lên thẻ cha — vì sao các thẻ con cũng đổi màu theo?",
        options: [
          "Trình duyệt copy khai báo sang từng con",
          "color là thuộc tính kế thừa — con chưa có màu riêng sẽ nhận theo cha",
          "Đó là lỗi của trình duyệt",
          "Chỉ xảy ra với thẻ div",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Chữ xám nhạt #ccc trên nền trắng bị chê 'khó đọc'. Vấn đề thuộc về khái niệm nào?",
        options: [
          "Độ phân giải màn hình",
          "Độ tương phản (contrast) giữa chữ và nền quá thấp — tiêu chuẩn WCAG khuyến nghị tối thiểu 4.5:1 cho chữ thường",
          "Font chữ quá mỏng",
          "Thiếu !important",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Ngoài chữ, giá trị của color còn được thuộc tính nào 'mượn' theo mặc định?",
        options: [
          "background-color",
          "border-color và outline-color khi không khai báo màu riêng (cùng currentColor)",
          "width",
          "Không thuộc tính nào",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có đoạn cảnh báo class canh-bao. Viết rule .canh-bao đặt màu chữ #b91c1c.",
        requirements: [
          { type: "selector", value: ".canh-bao" },
          { type: "value", selector: ".canh-bao", name: "color", value: "#b91c1c" },
        ],
        starterCode: "/* HTML căn cứ:\n<p class=\"canh-bao\">Mật khẩu sắp hết hạn</p>\n*/\n",
      },
    ],
  },
  {
    name: "background-color",
    topic: "Màu & nền",
    part: PART,
    description: "Màu nền của hộp — tô hết content và padding",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào đặt MÀU NỀN cho phần tử?",
        options: ["color", "background-color", "fill", "bgcolor"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Khối thông báo thành công cần nền xanh lá nhạt. Khai báo nào đúng?",
        options: [
          "background-color: #d1fae5;",
          "color: #d1fae5;",
          "border: #d1fae5;",
          "background-text: #d1fae5;",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn nền TRONG SUỐT để lộ lớp dưới, giá trị nào đúng?",
        options: ["background-color: white;", "background-color: transparent;", "background-color: 0;", "background-color: none;"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "background-color tô đến đâu trong box model?",
        options: [
          "Chỉ phần chữ",
          "Hết content và padding (bên trong border) — không tô margin",
          "Tô cả margin",
          "Chỉ phần content",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Muốn lớp phủ đen mờ 50% đè lên ảnh (vẫn thấy ảnh bên dưới), giá trị nền nào đúng?",
        options: [
          "background-color: black;",
          "background-color: rgba(0, 0, 0, 0.5);",
          "background-color: #000;",
          "background-color: gray;",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "background-color có kế thừa xuống con như color không?",
        options: [
          "Có, giống hệt color",
          "Không — nền mặc định của con là transparent nên NHÌN xuyên xuống nền cha, dễ tưởng nhầm là kế thừa",
          "Chỉ kế thừa trong bảng",
          "Chỉ kế thừa khi cùng class",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có khối thông báo class thanh-cong. Viết rule .thanh-cong đặt màu nền #d1fae5 và màu chữ #065f46.",
        requirements: [
          { type: "selector", value: ".thanh-cong" },
          { type: "value", selector: ".thanh-cong", name: "background-color", value: "#d1fae5" },
          { type: "value", selector: ".thanh-cong", name: "color", value: "#065f46" },
        ],
        starterCode: "/* HTML căn cứ:\n<div class=\"thanh-cong\">Đặt hàng thành công!</div>\n*/\n",
      },
    ],
  },
  {
    name: "background-image",
    topic: "Màu & nền",
    part: PART,
    description: "Dùng ảnh làm nền với url()",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Cú pháp đúng để đặt ảnh nen.jpg làm nền?",
        options: [
          "background-image: nen.jpg;",
          "background-image: url(nen.jpg);",
          "image: url(nen.jpg);",
          "src: nen.jpg;",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Ảnh nền mặc định hiển thị thế nào khi nhỏ hơn phần tử?",
        options: [
          "Tự kéo giãn cho vừa",
          "Lặp lại (repeat) cả ngang lẫn dọc cho kín",
          "Chỉ hiện một lần ở giữa",
          "Không hiển thị",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Tắt việc lặp ảnh nền dùng khai báo nào?",
        options: [
          "background-repeat: no-repeat;",
          "background-loop: none;",
          "repeat: 0;",
          "background-image: once;",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Hero section có ảnh nền + chữ trắng đè lên. Khi ảnh lỗi/chưa tải, chữ trắng biến mất trên nền trắng. Cách phòng?",
        options: [
          "Đợi ảnh tải xong mới hiện chữ",
          "Khai báo thêm background-color tối làm nền dự phòng dưới ảnh",
          "Dùng !important cho ảnh",
          "Không có cách nào",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Đường dẫn trong url() của file css được tính từ đâu?",
        options: [
          "Từ file HTML đang mở",
          "Từ vị trí của CHÍNH file CSS chứa khai báo đó",
          "Từ thư mục gốc ổ đĩa",
          "Từ thẻ <base> luôn luôn",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Có thể khai báo NHIỀU ảnh nền chồng lớp trên một phần tử không?",
        options: [
          "Không, mỗi phần tử một ảnh",
          "Được — liệt kê cách nhau dấu phẩy, ảnh khai báo TRƯỚC nằm TRÊN",
          "Được nhưng phải dùng JS",
          "Chỉ với thẻ div",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có hero class hero. Viết rule .hero đặt ảnh nền  background-image: url(nui.jpg)  và tắt lặp với  background-repeat: no-repeat.",
        requirements: [
          { type: "selector", value: ".hero" },
          { type: "value", selector: ".hero", name: "background-image", value: "url(nui.jpg)" },
          { type: "value", selector: ".hero", name: "background-repeat", value: "no-repeat" },
        ],
        starterCode: "/* HTML căn cứ:\n<section class=\"hero\">\n  <h1>Du lịch Đà Lạt</h1>\n</section>\n*/\n",
      },
    ],
  },
  {
    name: "background-size",
    topic: "Màu & nền",
    part: PART,
    description: "cover phủ kín (có thể cắt), contain hiện trọn (có thể hở)",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Muốn ảnh nền PHỦ KÍN toàn bộ phần tử (chấp nhận bị cắt bớt), giá trị nào đúng?",
        options: [
          "background-size: contain;",
          "background-size: cover;",
          "background-size: 100%;",
          "background-size: full;",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "background-size: contain  hoạt động thế nào?",
        options: [
          "Phủ kín và cắt phần thừa",
          "Hiện TRỌN VẸN ảnh bên trong phần tử — có thể thừa khoảng trống nếu tỷ lệ lệch",
          "Kéo méo ảnh cho khít",
          "Thu nhỏ ảnh còn một nửa",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Hero banner full màn hình cần ảnh không hở mép dù màn nào. Chọn giá trị nào?",
        options: ["contain", "cover", "auto", "repeat"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác biệt cốt lõi giữa cover và contain?",
        options: [
          "cover cho ảnh nhỏ, contain cho ảnh lớn",
          "cover ưu tiên PHỦ KÍN (chấp nhận cắt ảnh); contain ưu tiên HIỆN TRỌN ảnh (chấp nhận hở nền)",
          "cover nhanh hơn contain",
          "contain chỉ chạy với PNG",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "background-size: 100% 100%  khác gì cover?",
        options: [
          "Giống hệt nhau",
          "100% 100% kéo ảnh khít cả hai chiều nên MÉO ảnh khi tỷ lệ lệch; cover giữ nguyên tỷ lệ và cắt bớt",
          "100% 100% giữ tỷ lệ tốt hơn",
          "cover làm méo ảnh",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Logo dạng pattern nhỏ muốn hiển thị đúng kích thước gốc làm nền lặp — dùng giá trị nào?",
        options: [
          "cover",
          "auto (mặc định) — giữ kích thước thật của ảnh",
          "contain",
          "0",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có banner class banner đã có ảnh nền. Viết rule .banner đặt  background-size: cover  và  background-position: center.",
        requirements: [
          { type: "selector", value: ".banner" },
          { type: "value", selector: ".banner", name: "background-size", value: "cover" },
          { type: "value", selector: ".banner", name: "background-position", value: "center" },
        ],
        starterCode: "/* HTML căn cứ:\n<div class=\"banner\" style=\"background-image: url(bien.jpg)\">\n  <h2>Khuyến mãi hè</h2>\n</div>\n*/\n",
      },
    ],
  },
  {
    name: "background-position",
    topic: "Màu & nền",
    part: PART,
    description: "Neo vị trí ảnh nền: center, top, góc, tọa độ",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Căn ảnh nền vào CHÍNH GIỮA phần tử, khai báo nào đúng?",
        options: [
          "background-position: center;",
          "background-align: middle;",
          "background-center: true;",
          "position: center;",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "background-position: top right  neo ảnh vào đâu?",
        options: ["Góc trên bên phải", "Góc dưới bên phải", "Chính giữa cạnh phải", "Góc trên bên trái"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Bạn đặt background-image nhưng chưa khai báo background-position. Giá trị MẶC ĐỊNH của nó là gì?",
        options: ["center", "0% 0% (góc trên trái)", "bottom", "50% 50%"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Ảnh chân dung bị cover cắt mất phần ĐẦU người. Chỉnh gì để ưu tiên giữ phần trên ảnh?",
        options: [
          "background-position: bottom;",
          "background-position: top; — neo mép trên, phần bị cắt dồn xuống dưới",
          "background-size: contain;",
          "Tăng chiều cao phần tử là cách duy nhất",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "background-position: 20px 40px  nghĩa là gì?",
        options: [
          "Ảnh cách mép trái 20px và mép trên 40px",
          "Ảnh cách mép phải 20px",
          "Ảnh to 20×40px",
          "Lặp ảnh mỗi 20px",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khi nào background-position phát huy rõ nhất tác dụng?",
        options: [
          "Khi ảnh lặp kín repeat",
          "Khi ảnh KHÔNG phủ vừa khít phần tử (no-repeat, cover bị cắt...) — cần quyết định phần nào của ảnh được ưu tiên nhìn thấy",
          "Khi nền là màu đơn sắc",
          "Không bao giờ cần",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có thẻ chân dung class chan-dung dùng ảnh nền. Viết rule .chan-dung đặt  background-position: top  và  background-repeat: no-repeat.",
        requirements: [
          { type: "selector", value: ".chan-dung" },
          { type: "value", selector: ".chan-dung", name: "background-position", value: "top" },
          { type: "value", selector: ".chan-dung", name: "background-repeat", value: "no-repeat" },
        ],
        starterCode: "/* HTML căn cứ:\n<div class=\"chan-dung\" style=\"background-image: url(giam-doc.jpg)\"></div>\n*/\n",
      },
    ],
  },
  {
    name: "gradient",
    topic: "Màu & nền",
    part: PART,
    description: "Nền chuyển màu với linear-gradient / radial-gradient",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Tạo nền chuyển dần từ màu này sang màu khác dùng gì?",
        options: [
          "background-image: linear-gradient(...);",
          "background-color: gradient;",
          "color-transition: ...;",
          "background-fade: ...;",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "linear-gradient(to right, red, blue)  chuyển màu theo hướng nào?",
        options: [
          "Từ trên xuống dưới",
          "Từ trái (red) sang phải (blue)",
          "Từ giữa tỏa ra",
          "Chéo 45 độ",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Gradient tỏa TRÒN từ tâm ra ngoài dùng hàm nào?",
        options: ["linear-gradient", "radial-gradient", "circle-gradient", "round-gradient"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao gradient khai báo qua background-image chứ không phải background-color?",
        options: [
          "Do thói quen lịch sử",
          "Gradient là ẢNH do trình duyệt vẽ ra (image), không phải một giá trị màu đơn — nên nó dùng được mọi tính năng của ảnh nền",
          "background-color không tồn tại",
          "Để tương thích IE",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "linear-gradient(45deg, ...)  — góc 45deg trỏ hướng nào?",
        options: [
          "Từ trên xuống",
          "Chéo lên góc trên-phải (0deg hướng lên trên, góc xoay thuận kim đồng hồ)",
          "Chéo xuống góc dưới-phải",
          "Ngang sang trái",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Tạo dải màu CÓ ĐIỂM DỪNG sắc nét (không hòa trộn) như cờ kẻ sọc, cách nào đúng?",
        options: [
          "Không thể làm bằng gradient",
          "Đặt hai màu kề nhau cùng vị trí dừng: linear-gradient(red 50%, blue 50%)",
          "Dùng ba màu trở lên",
          "Thêm !important",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có nút class nut-cam. Viết rule .nut-cam đặt nền chuyển màu:  background-image: linear-gradient(to right, #f97316, #ef4444).",
        requirements: [
          { type: "selector", value: ".nut-cam" },
          {
            type: "value",
            selector: ".nut-cam",
            name: "background-image",
            value: "linear-gradient(to right, #f97316, #ef4444)",
          },
        ],
        starterCode: "/* HTML căn cứ:\n<button class=\"nut-cam\">Đăng ký ngay</button>\n*/\n",
      },
    ],
  },
  {
    name: "opacity",
    topic: "Màu & nền",
    part: PART,
    description: "Độ mờ của TOÀN BỘ phần tử, từ 0 (ẩn) đến 1 (rõ)",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào chỉnh độ mờ của cả phần tử?",
        options: ["transparency", "opacity", "alpha", "fade"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "opacity: 0.5  nghĩa là gì?",
        options: [
          "Phần tử nhỏ đi một nửa",
          "Phần tử mờ 50% — nhìn xuyên thấy lớp dưới",
          "Chỉ nền mờ 50%",
          "Phần tử ẩn hoàn toàn",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Giá trị opacity nằm trong khoảng nào?",
        options: ["0 đến 100", "0 (ẩn) đến 1 (rõ hoàn toàn)", "-1 đến 1", "1 đến 10"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác nhau giữa  opacity: 0.5  trên phần tử và nền  rgba(..., 0.5)?",
        options: [
          "Như nhau",
          "opacity làm mờ TOÀN BỘ phần tử kể cả chữ và con bên trong; rgba chỉ làm mờ riêng màu nền, chữ vẫn rõ",
          "rgba làm mờ cả chữ",
          "opacity chỉ mờ chữ",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Phần tử  opacity: 0  còn bấm được không?",
        options: [
          "Không, như display: none",
          "Vẫn bấm được — nó chỉ vô hình nhưng vẫn chiếm chỗ và nhận sự kiện (khác display: none)",
          "Chỉ bấm được trên mobile",
          "Tùy trình duyệt",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Ứng dụng phổ biến của opacity trong tương tác?",
        options: [
          "Đổi font khi hover",
          "Làm nút/ảnh mờ nhẹ khi hover hoặc thể hiện trạng thái disabled (mờ = không khả dụng)",
          "Tăng độ tương phản",
          "Đổi kích thước ảnh",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có nút bị khóa class nut-khoa. Viết rule .nut-khoa đặt  opacity: 0.4  và  cursor: not-allowed.",
        requirements: [
          { type: "selector", value: ".nut-khoa" },
          { type: "value", selector: ".nut-khoa", name: "opacity", value: "0.4" },
          { type: "value", selector: ".nut-khoa", name: "cursor", value: "not-allowed" },
        ],
        starterCode: "/* HTML căn cứ:\n<button class=\"nut-khoa\" disabled>Hết hàng</button>\n*/\n",
      },
    ],
  },

  // ===== CHƯƠNG 7: CHỮ & FONT =====
  {
    name: "font-family",
    topic: "Chữ & font",
    part: PART,
    description: "Chọn font chữ với danh sách dự phòng (font stack)",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào đổi KIỂU CHỮ (font) của phần tử?",
        options: ["font-style", "font-family", "text-font", "typeface"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Vì sao viết  font-family: Arial, Helvetica, sans-serif  (nhiều font cách nhau dấu phẩy)?",
        options: [
          "Trộn ba font với nhau",
          "Danh sách dự phòng: máy không có Arial sẽ thử Helvetica, cuối cùng là font sans-serif bất kỳ của hệ thống",
          "Mỗi đoạn văn một font",
          "Bắt buộc đủ 3 font",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Tên font CÓ KHOẢNG TRẮNG như Be Vietnam Pro viết thế nào?",
        options: [
          "Viết liền BeVietnamPro",
          "Bọc trong quote: font-family: \"Be Vietnam Pro\", sans-serif;",
          "Thay khoảng trắng bằng gạch ngang",
          "Không dùng được font có khoảng trắng",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "serif và sans-serif khác nhau thế nào?",
        options: [
          "serif là font đậm, sans-serif là font nhạt",
          "serif có CHÂN ở nét chữ (cảm giác cổ điển, báo in); sans-serif KHÔNG chân (hiện đại, phổ biến trên màn hình)",
          "serif chỉ dùng cho tiếng Anh",
          "sans-serif là font viết tay",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao phần tử cuối của font stack nên là từ khóa chung (sans-serif, serif, monospace)?",
        options: [
          "Để file css ngắn hơn",
          "Đó là lưới an toàn cuối: nếu mọi font chỉ định đều không có, trình duyệt vẫn chọn đúng NHÓM font thay vì font mặc định tùy ý",
          "Bắt buộc của cú pháp",
          "Để tăng tốc tải font",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khối hiển thị CODE nên dùng nhóm font nào, vì sao?",
        options: [
          "serif — trang trọng",
          "monospace — mọi ký tự RỘNG BẰNG NHAU nên các cột thẳng hàng, dễ đọc code",
          "cursive — mềm mại",
          "sans-serif — hiện đại",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có khối code class khoi-code. Viết rule .khoi-code đặt  font-family: monospace  và màu nền #1e293b.",
        requirements: [
          { type: "selector", value: ".khoi-code" },
          { type: "value", selector: ".khoi-code", name: "font-family", value: "monospace" },
          { type: "value", selector: ".khoi-code", name: "background-color", value: "#1e293b" },
        ],
        starterCode: "/* HTML căn cứ:\n<pre class=\"khoi-code\">console.log(\"hi\")</pre>\n*/\n",
      },
    ],
  },
  {
    name: "font-size",
    topic: "Chữ & font",
    part: PART,
    description: "Cỡ chữ — nên dùng rem để tôn trọng cài đặt người dùng",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào đổi CỠ CHỮ?",
        options: ["text-size", "font-size", "size", "font-scale"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Cỡ chữ mặc định của trình duyệt (khi chưa chỉnh gì) là bao nhiêu?",
        options: ["12px", "16px", "20px", "14px"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Chú thích ảnh cần chữ NHỎ hơn nội dung chính. Khai báo hợp lý?",
        options: [
          "font-size: 0.875rem;",
          "font-size: 2rem;",
          "font-weight: small;",
          "text-size: tiny;",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao nên đặt cỡ chữ bằng rem thay vì px?",
        options: [
          "rem hiển thị nét hơn",
          "rem co giãn theo cài đặt cỡ chữ của người dùng — người mắt kém tăng cỡ mặc định thì chữ trang bạn cũng to theo",
          "px sắp bị loại bỏ",
          "rem viết ngắn hơn",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao KHÔNG nên chọn h1/h2 chỉ để lấy cỡ chữ to?",
        options: [
          "h1 không đổi được cỡ chữ",
          "Cấp tiêu đề mang Ý NGHĨA cấu trúc (SEO, máy đọc màn hình) — cỡ chữ là việc của CSS; chọn đúng cấp rồi chỉnh font-size",
          "h2 luôn nhỏ hơn p",
          "Tiêu đề không nhận font-size",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Cỡ chữ thân bài (body text) cho web tiếng Việt thường khuyến nghị tối thiểu bao nhiêu?",
        options: [
          "10px cho gọn",
          "16px (1rem) — nhỏ hơn dễ gây mỏi mắt, đặc biệt trên mobile",
          "24px trở lên",
          "Không có khuyến nghị",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có chú thích ảnh class chu-thich. Viết rule .chu-thich đặt font-size 0.875rem và màu chữ gray.",
        requirements: [
          { type: "selector", value: ".chu-thich" },
          { type: "value", selector: ".chu-thich", name: "font-size", value: "0.875rem" },
          { type: "value", selector: ".chu-thich", name: "color", value: "gray" },
        ],
        starterCode: "/* HTML căn cứ:\n<figcaption class=\"chu-thich\">Hồ Gươm nhìn từ trên cao</figcaption>\n*/\n",
      },
    ],
  },
  {
    name: "font-weight",
    topic: "Chữ & font",
    part: PART,
    description: "Độ đậm của chữ: 100→900, normal=400, bold=700",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào làm chữ ĐẬM?",
        options: ["font-bold", "font-weight", "text-strong", "font-style"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "font-weight: bold  tương đương giá trị số nào?",
        options: ["400", "700", "900", "500"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Chữ thường (không đậm) là giá trị nào?",
        options: ["normal (= 400)", "thin", "regular500", "0"],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Thang số 100–900 của font-weight có ý nghĩa gì?",
        options: [
          "Cỡ chữ theo phần trăm",
          "Các mức đậm từ mảnh (100) đến rất đậm (900) — font phải CÓ SẴN các mức đó mới hiển thị đúng",
          "Độ nghiêng",
          "Khoảng cách chữ",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Đặt  font-weight: 300  nhưng chữ trông y như 400. Nguyên nhân thường gặp?",
        options: [
          "300 không hợp lệ",
          "Font đang dùng KHÔNG có bản weight 300 — trình duyệt rơi về mức gần nhất hoặc giả lập; cần nạp đúng biến thể font",
          "Phải viết light thay vì 300",
          "Trình duyệt chặn font mỏng",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác nhau giữa thẻ <strong> và  font-weight: bold?",
        options: [
          "Hoàn toàn giống nhau",
          "<strong> mang Ý NGHĨA nhấn mạnh (máy đọc màn hình nhận biết); font-weight chỉ là vẻ ngoài — chữ đậm trang trí thuần túy nên dùng CSS",
          "<strong> đậm hơn",
          "font-weight chỉ dùng cho tiêu đề",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có giá sản phẩm class gia-tien. Viết rule .gia-tien đặt  font-weight: 700  và màu chữ #e34f26.",
        requirements: [
          { type: "selector", value: ".gia-tien" },
          { type: "value", selector: ".gia-tien", name: "font-weight", value: "700" },
          { type: "value", selector: ".gia-tien", name: "color", value: "#e34f26" },
        ],
        starterCode: "/* HTML căn cứ:\n<span class=\"gia-tien\">299.000đ</span>\n*/\n",
      },
    ],
  },
  {
    name: "font-style",
    topic: "Chữ & font",
    part: PART,
    description: "Chữ nghiêng (italic) và shorthand font",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Làm chữ NGHIÊNG dùng khai báo nào?",
        options: [
          "font-style: italic;",
          "font-weight: italic;",
          "text-style: slope;",
          "font-italic: true;",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Bỏ nghiêng (về chữ đứng) dùng giá trị nào?",
        options: ["straight", "normal", "none", "regular"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Trích dẫn sách trong bài viết thường để kiểu chữ gì?",
        options: ["Gạch chân", "Nghiêng (italic) — quy ước trình bày quen thuộc", "Viết hoa toàn bộ", "Đậm 900"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "italic và oblique khác nhau thế nào?",
        options: [
          "Như nhau tuyệt đối",
          "italic dùng BẢN THIẾT KẾ nghiêng riêng của font (nét chữ khác); oblique chỉ NGHIÊNG CƠ HỌC chữ đứng",
          "oblique nghiêng nhiều hơn",
          "italic chỉ cho tiếng Anh",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Shorthand  font: italic 700 1.25rem/1.6 Arial, sans-serif  — phần  1.25rem/1.6  là gì?",
        options: [
          "Cỡ chữ / độ đậm",
          "font-size / line-height viết gọn bằng dấu gạch chéo",
          "Chiều rộng / chiều cao",
          "Khoảng cách chữ / từ",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Thẻ <em> mặc định nghiêng. Khác gì với span đặt font-style: italic?",
        options: [
          "Không khác gì",
          "<em> mang ý nghĩa NHẤN MẠNH ngữ nghĩa; CSS italic chỉ là trình bày — nghiêng trang trí (tên tác phẩm, từ nước ngoài) nên dùng CSS hoặc <i>",
          "<em> nghiêng nhiều hơn",
          "span không nghiêng được",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có lời trích class loi-trich. Viết rule .loi-trich đặt  font-style: italic  và màu chữ #475569.",
        requirements: [
          { type: "selector", value: ".loi-trich" },
          { type: "value", selector: ".loi-trich", name: "font-style", value: "italic" },
          { type: "value", selector: ".loi-trich", name: "color", value: "#475569" },
        ],
        starterCode: "/* HTML căn cứ:\n<blockquote class=\"loi-trich\">Học, học nữa, học mãi.</blockquote>\n*/\n",
      },
    ],
  },
  {
    name: "line-height",
    topic: "Chữ & font",
    part: PART,
    description: "Khoảng cách dòng — chìa khóa của văn bản dễ đọc",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào chỉnh KHOẢNG CÁCH GIỮA CÁC DÒNG chữ?",
        options: ["letter-spacing", "line-height", "word-spacing", "text-gap"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "line-height: 1.6  nghĩa là gì?",
        options: [
          "Cao 1.6px",
          "Chiều cao dòng bằng 1.6 LẦN cỡ chữ hiện tại",
          "1.6cm mỗi dòng",
          "Cách nhau 16px cố định",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Đoạn văn dày đặc khó đọc, các dòng dính nhau. Chỉnh gì đầu tiên?",
        options: ["Tăng font-weight", "Tăng line-height (vd 1.6–1.8)", "Đổi màu chữ", "Tăng letter-spacing"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao giá trị KHÔNG ĐƠN VỊ (1.6) được khuyên dùng hơn 26px hay 160%?",
        options: [
          "Viết ngắn hơn",
          "Giá trị không đơn vị kế thừa dưới dạng HỆ SỐ — con tự tính theo cỡ chữ CỦA NÓ; px/% kế thừa giá trị đã tính cứng, chữ to trong con sẽ bị dòng đè nhau",
          "Trình duyệt cũ không hiểu px",
          "Không khác gì nhau",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Tiêu đề lớn nhiều dòng nên để line-height thế nào so với thân bài?",
        options: [
          "Cao hơn (2.0+)",
          "THẤP hơn (1.1–1.3) — chữ to sẵn có khoảng trống quang học, line-height cao làm các dòng tiêu đề rời rạc",
          "Giống hệt thân bài",
          "Luôn để 1.0",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Mẹo căn giữa DỌC chữ một dòng trong nút cao cố định (trước thời flexbox)?",
        options: [
          "margin: auto",
          "Đặt line-height BẰNG chiều cao nút — dòng chữ tự nằm giữa",
          "padding-top: 50%",
          "vertical-align: center",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có bài viết class than-bai. Viết rule .than-bai đặt  line-height: 1.7  và  font-size: 1rem.",
        requirements: [
          { type: "selector", value: ".than-bai" },
          { type: "value", selector: ".than-bai", name: "line-height", value: "1.7" },
          { type: "value", selector: ".than-bai", name: "font-size", value: "1rem" },
        ],
        starterCode: "/* HTML căn cứ:\n<article class=\"than-bai\">\n  <p>Nội dung bài viết dài nhiều dòng...</p>\n</article>\n*/\n",
      },
    ],
  },
  {
    name: "text-align",
    topic: "Chữ & font",
    part: PART,
    description: "Căn chữ trong khối: left, center, right, justify",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Căn GIỮA dòng tiêu đề dùng khai báo nào?",
        options: [
          "text-align: center;",
          "align: middle;",
          "margin: center;",
          "text-position: center;",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "text-align căn cái gì?",
        options: [
          "Cả khối hộp",
          "Nội dung INLINE (chữ, ảnh inline) bên trong khối",
          "Vị trí khối so với cha",
          "Thứ tự các thẻ",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Cột số tiền trong bảng nên căn về đâu cho dễ so sánh?",
        options: ["Trái", "Phải (text-align: right) — hàng đơn vị thẳng cột", "Giữa", "Đều hai bên"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "text-align: justify  làm gì và cần lưu ý gì?",
        options: [
          "Căn phải toàn bộ",
          "Giãn chữ cho thẳng CẢ hai mép — nhưng cột hẹp dễ sinh 'dòng sông' khoảng trắng khó đọc",
          "Thu hẹp khoảng cách chữ",
          "Tự xuống dòng theo từ",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao  text-align: center  trên div KHÔNG căn giữa được một div con có width cố định?",
        options: [
          "Phải thêm !important",
          "text-align chỉ tác động nội dung inline; div con là BLOCK — căn giữa khối phải dùng margin: 0 auto (hoặc flex)",
          "Div con phải có id",
          "Trình duyệt lỗi",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Văn bản dài nên căn gì làm mặc định?",
        options: [
          "justify cho vuông vắn",
          "Trái (left) — mép trái thẳng giúp mắt tìm đầu dòng nhanh, nghiên cứu đọc hiểu ủng hộ",
          "Giữa cho cân đối",
          "Phải cho lạ mắt",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có tiêu đề khu vực class tieu-de-muc. Viết rule .tieu-de-muc căn giữa chữ (text-align: center) và  font-size: 1.5rem.",
        requirements: [
          { type: "selector", value: ".tieu-de-muc" },
          { type: "value", selector: ".tieu-de-muc", name: "text-align", value: "center" },
          { type: "value", selector: ".tieu-de-muc", name: "font-size", value: "1.5rem" },
        ],
        starterCode: "/* HTML căn cứ:\n<h2 class=\"tieu-de-muc\">Sản phẩm nổi bật</h2>\n*/\n",
      },
    ],
  },
  {
    name: "text-decoration",
    topic: "Chữ & font",
    part: PART,
    description: "Gạch chân/gạch ngang chữ — và cách bỏ gạch chân link",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Bỏ GẠCH CHÂN mặc định của link dùng khai báo nào?",
        options: [
          "text-decoration: none;",
          "underline: false;",
          "text-underline: 0;",
          "link-style: plain;",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Giá nay đã giảm — muốn GẠCH NGANG giá cũ dùng giá trị nào?",
        options: ["underline", "line-through", "overline", "strike"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Thêm gạch chân cho chữ thường dùng khai báo nào?",
        options: [
          "text-decoration: underline;",
          "border-bottom: text;",
          "font-style: underline;",
          "text-line: under;",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Bỏ gạch chân link điều hướng (menu) có ổn không về khả dụng?",
        options: [
          "Không bao giờ được bỏ",
          "Ổn khi ngữ cảnh đã rõ là link (menu, nút) — nhưng link NẰM TRONG đoạn văn nên giữ gạch chân/dấu hiệu rõ để không lẫn với chữ thường",
          "Bỏ thoải mái mọi nơi",
          "Chỉ bỏ được trên mobile",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Có thể đổi MÀU và KIỂU của đường gạch riêng (không đổi màu chữ) không?",
        options: [
          "Không, gạch luôn cùng màu chữ",
          "Được: text-decoration-color và text-decoration-style (wavy, dotted...) — vd gạch sóng đỏ báo lỗi chính tả",
          "Chỉ đổi được độ dày",
          "Phải dùng border-bottom",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác nhau giữa gạch chân bằng text-decoration và border-bottom?",
        options: [
          "Như nhau",
          "text-decoration vẽ sát chữ và ngắt theo chữ; border-bottom kẻ dưới CẢ hộp (cách chữ hơn, chạy hết chiều rộng) — mỗi cái hợp một mục đích",
          "border-bottom không dùng được cho chữ",
          "text-decoration dày hơn",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có giá cũ class gia-cu. Viết rule .gia-cu gạch ngang chữ (text-decoration: line-through) và màu chữ gray.",
        requirements: [
          { type: "selector", value: ".gia-cu" },
          { type: "value", selector: ".gia-cu", name: "text-decoration", value: "line-through" },
          { type: "value", selector: ".gia-cu", name: "color", value: "gray" },
        ],
        starterCode: "/* HTML căn cứ:\n<span class=\"gia-cu\">399.000đ</span> <span>299.000đ</span>\n*/\n",
      },
    ],
  },
  {
    name: "text-transform",
    topic: "Chữ & font",
    part: PART,
    description: "Đổi kiểu hoa/thường và giãn cách ký tự letter-spacing",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Hiển thị chữ TOÀN HOA mà không sửa nội dung HTML, dùng gì?",
        options: [
          "text-transform: uppercase;",
          "font-case: upper;",
          "text-style: caps;",
          "Phải gõ lại chữ hoa trong HTML",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "text-transform: capitalize  làm gì?",
        options: [
          "Viết hoa toàn bộ",
          "Viết hoa CHỮ ĐẦU mỗi từ",
          "Viết thường toàn bộ",
          "Viết hoa chữ đầu câu",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào GIÃN khoảng cách giữa các KÝ TỰ?",
        options: ["word-spacing", "letter-spacing", "line-height", "text-indent"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao làm chữ hoa bằng CSS tốt hơn gõ thẳng chữ hoa vào HTML?",
        options: [
          "CSS render chữ hoa đẹp hơn",
          "Nội dung gốc giữ nguyên ngữ nghĩa — đổi ý thì chỉ sửa CSS một chỗ, máy đọc màn hình không bị đọc 'từng-chữ-cái' như một số từ viết hoa lạ",
          "HTML không cho phép chữ hoa",
          "Không có khác biệt",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Nhãn nhỏ TOÀN HOA (badge, nhãn chuyên mục) thường đi kèm chỉnh gì để dễ đọc?",
        options: [
          "Tăng line-height",
          "Tăng nhẹ letter-spacing (vd 0.05em) — chữ hoa đứng sít nhau khó đọc, giãn ra thoáng hơn",
          "Giảm font-weight về 100",
          "Thêm gạch chân",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "letter-spacing nên dùng đơn vị nào để giãn cách tỷ lệ theo cỡ chữ?",
        options: [
          "px — cố định mọi nơi",
          "em — giãn cách tự to nhỏ theo font-size của chính phần tử",
          "vh",
          "% không đơn vị",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có nhãn chuyên mục class nhan-muc. Viết rule .nhan-muc viết hoa toàn bộ (text-transform: uppercase) và giãn ký tự  letter-spacing: 0.05em.",
        requirements: [
          { type: "selector", value: ".nhan-muc" },
          { type: "value", selector: ".nhan-muc", name: "text-transform", value: "uppercase" },
          { type: "value", selector: ".nhan-muc", name: "letter-spacing", value: "0.05em" },
        ],
        starterCode: "/* HTML căn cứ:\n<span class=\"nhan-muc\">Thể thao</span>\n*/\n",
      },
    ],
  },
];
