import type { CssSeedTag } from "./types";

const PART = "Giao diện";

// PHẦN 2 — Chương 8 (Trang trí) + Chương 9 (Ảnh & đồ họa)
export const PART2_CHUONG_8_9: CssSeedTag[] = [
  // ===== CHƯƠNG 8: TRANG TRÍ =====
  {
    name: "box-shadow",
    topic: "Trang trí",
    part: PART,
    description: "Bóng đổ quanh hộp: x y blur (spread) màu",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào tạo BÓNG ĐỔ cho hộp?",
        options: ["shadow", "box-shadow", "drop-shadow", "element-shadow"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Trong  box-shadow: 0 4px 8px rgba(0,0,0,0.2)  — số 4px là gì?",
        options: [
          "Độ lệch NGANG của bóng",
          "Độ lệch DỌC của bóng (dương = xuống dưới)",
          "Độ nhòe",
          "Độ lan",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Số thứ ba (8px trong 0 4px 8px) điều khiển gì?",
        options: ["Độ lệch dọc", "Độ NHÒE (blur) — càng lớn bóng càng mềm", "Màu bóng", "Số lớp bóng"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao bóng đổ thực tế hay dùng rgba thay vì màu đặc?",
        options: [
          "rgba render nhanh hơn",
          "Bóng bán trong suốt hòa với MỌI màu nền bên dưới trông tự nhiên; bóng đen đặc trông như vết dán",
          "Màu đặc không hợp lệ trong box-shadow",
          "Để tiết kiệm ký tự",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Giá trị  inset  trong box-shadow làm gì?",
        options: [
          "Tăng độ nhòe",
          "Đổ bóng VÀO TRONG hộp (lõm xuống) thay vì ra ngoài",
          "Bóng đổ bốn phía",
          "Tắt bóng",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Thẻ sản phẩm muốn cảm giác 'nổi lên' khi hover — pattern phổ biến?",
        options: [
          "Tăng width",
          "Tăng box-shadow (bóng to/mềm hơn) kết hợp dịch nhẹ translateY âm",
          "Đổi font",
          "Thêm gạch chân",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có thẻ sản phẩm class the-hang. Viết rule .the-hang đặt bóng  box-shadow: 0 4px 12px rgba(0,0,0,0.15)  và nền white.",
        requirements: [
          { type: "selector", value: ".the-hang" },
          { type: "value", selector: ".the-hang", name: "box-shadow", value: "0 4px 12px rgba(0,0,0,0.15)" },
          { type: "value", selector: ".the-hang", name: "background-color", value: "white" },
        ],
        starterCode: "/* HTML căn cứ:\n<div class=\"the-hang\">\n  <h3>Bàn phím cơ</h3>\n</div>\n*/\n",
      },
    ],
  },
  {
    name: "text-shadow",
    topic: "Trang trí",
    part: PART,
    description: "Bóng cho chữ — cứu chữ trắng trên ảnh nền sáng",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào tạo bóng cho CHỮ?",
        options: ["font-shadow", "text-shadow", "box-shadow", "letter-shadow"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Cú pháp  text-shadow: 1px 1px 3px black  gồm những phần nào?",
        options: [
          "lệch-ngang lệch-dọc độ-nhòe màu",
          "trên phải dưới trái",
          "cỡ đậm nhòe màu",
          "x y width màu",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "text-shadow KHÁC box-shadow ở điểm nào?",
        options: [
          "text-shadow không có độ nhòe",
          "text-shadow đổ bóng theo NÉT CHỮ; box-shadow đổ theo khung HỘP chữ nhật",
          "text-shadow chỉ màu đen",
          "Không khác gì",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Chữ trắng đè trên ảnh có vùng sáng bị 'chìm'. Cách cứu nhanh bằng text-shadow?",
        options: [
          "Tăng font-size",
          "Thêm bóng tối mềm quanh chữ (vd 0 1px 4px rgba(0,0,0,0.6)) — tạo viền tương phản tách chữ khỏi nền",
          "Đổi chữ thành màu vàng",
          "Thêm gạch chân",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "text-shadow có nhận NHIỀU LỚP bóng không?",
        options: [
          "Không, một lớp duy nhất",
          "Có — liệt kê cách nhau dấu phẩy, tạo hiệu ứng viền chữ, neon, 3D...",
          "Tối đa hai lớp",
          "Chỉ trong Firefox",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Có nên đổ bóng đậm cho chữ THÂN BÀI dài không?",
        options: [
          "Nên, trông nổi bật",
          "Không — bóng làm nét chữ nhỏ bị nhòe, đọc lâu mỏi mắt; text-shadow hợp với tiêu đề/chữ to trang trí",
          "Bắt buộc cho mọi chữ",
          "Chỉ nên trên mobile",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có tiêu đề trên ảnh class tieu-de-anh. Viết rule .tieu-de-anh đặt màu chữ white và bóng  text-shadow: 0 2px 6px rgba(0,0,0,0.7).",
        requirements: [
          { type: "selector", value: ".tieu-de-anh" },
          { type: "value", selector: ".tieu-de-anh", name: "color", value: "white" },
          { type: "value", selector: ".tieu-de-anh", name: "text-shadow", value: "0 2px 6px rgba(0,0,0,0.7)" },
        ],
        starterCode: "/* HTML căn cứ:\n<h1 class=\"tieu-de-anh\">Khám phá Sapa</h1>\n(đè trên ảnh nền sáng)\n*/\n",
      },
    ],
  },
  {
    name: "border-radius",
    topic: "Trang trí",
    part: PART,
    description: "Bo góc hộp — từ bo nhẹ đến hình tròn 50%",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào BO TRÒN GÓC của hộp?",
        options: ["corner-round", "border-radius", "box-corner", "round"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Biến ảnh VUÔNG thành hình TRÒN dùng giá trị nào?",
        options: ["border-radius: 100px;", "border-radius: 50%;", "border-radius: circle;", "border-radius: round;"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "border-radius: 8px  tác động thế nào?",
        options: [
          "Chỉ bo hai góc trên",
          "Bo cả BỐN góc với bán kính 8px",
          "Bo góc dưới trái",
          "Tạo viền 8px",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Nút dạng 'viên thuốc' (pill) hai đầu tròn hẳn làm thế nào?",
        options: [
          "border-radius: 50%",
          "border-radius lớn hơn nửa chiều cao nút (vd 999px) — hai đầu thành bán nguyệt",
          "border-radius: pill",
          "Không làm được bằng CSS",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "border-radius 4 giá trị  border-radius: 8px 0 8px 0  bo những góc nào?",
        options: [
          "Trên-trái và dưới-phải (thứ tự: trên-trái, trên-phải, dưới-phải, dưới-trái)",
          "Hai góc trên",
          "Hai góc trái",
          "Trên-phải và dưới-trái",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Ảnh bên trong thẻ bo góc vẫn LÒI GÓC VUÔNG che mất bo. Cách xử lý quen thuộc?",
        options: [
          "Tăng border-radius của thẻ",
          "Thêm overflow: hidden cho thẻ cha (cắt phần con thừa ra ngoài góc bo) hoặc bo trực tiếp ảnh",
          "Giảm cỡ ảnh",
          "Dùng !important",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có hộp khuyến mãi class hop-km. Viết rule .hop-km bo góc  border-radius: 12px  và đặt  overflow: hidden.",
        requirements: [
          { type: "selector", value: ".hop-km" },
          { type: "value", selector: ".hop-km", name: "border-radius", value: "12px" },
          { type: "value", selector: ".hop-km", name: "overflow", value: "hidden" },
        ],
        starterCode: "/* HTML căn cứ:\n<div class=\"hop-km\">\n  <img src=\"sale.jpg\" alt=\"Khuyến mãi\">\n</div>\n*/\n",
      },
    ],
  },
  {
    name: "outline",
    topic: "Trang trí",
    part: PART,
    description: "Viền focus không chiếm chỗ — đừng xóa nếu không thay thế",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Viền xanh xuất hiện quanh ô input khi bấm Tab vào là gì?",
        options: ["border mặc định", "outline (viền focus) của trình duyệt", "box-shadow", "text-decoration"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "outline khác border ở điểm cốt lõi nào?",
        options: [
          "outline chỉ có màu xanh",
          "outline vẽ ĐÈ ra ngoài, KHÔNG chiếm chỗ trong layout — bật/tắt không xô lệch gì",
          "outline dày hơn border",
          "outline nằm trong padding",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Cú pháp outline giống thuộc tính nào?",
        options: [
          "background: màu ảnh vị trí",
          "border: độ-dày kiểu màu (vd outline: 2px solid blue)",
          "margin: 4 giá trị",
          "font: cỡ/cao font",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao  outline: none  tràn lan bị coi là lỗi accessibility nghiêm trọng?",
        options: [
          "Làm trang chậm",
          "Người điều hướng bằng BÀN PHÍM mất dấu hiệu duy nhất cho biết đang đứng ở đâu — xóa thì phải thay bằng focus style khác rõ ràng",
          "Trình duyệt cấm outline: none",
          "Outline giúp SEO",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Pseudo-class  :focus-visible  hay dùng với outline để làm gì?",
        options: [
          "Tăng độ dày outline",
          "Chỉ hiện viền focus khi điều hướng bằng BÀN PHÍM, ẩn khi click chuột — cân bằng thẩm mỹ và accessibility",
          "Đổi màu outline ngẫu nhiên",
          "Outline hiện cả khi hover",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "outline-offset làm gì?",
        options: [
          "Xoay outline",
          "Đẩy viền outline ra XA mép phần tử một khoảng — tạo khoảng thở giữa viền và hộp",
          "Làm mờ outline",
          "Đổi outline thành nét đứt",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có ô tìm kiếm class o-tim. Viết rule cho trạng thái focus (selector .o-tim:focus) đặt  outline: 2px solid #e34f26  và  outline-offset: 2px.",
        requirements: [
          { type: "selector", value: ".o-tim:focus" },
          { type: "value", selector: ".o-tim:focus", name: "outline", value: "2px solid #e34f26" },
          { type: "value", selector: ".o-tim:focus", name: "outline-offset", value: "2px" },
        ],
        starterCode: "/* HTML căn cứ:\n<input class=\"o-tim\" type=\"search\" placeholder=\"Tìm sản phẩm\">\n*/\n",
      },
    ],
  },
  {
    name: "cursor",
    topic: "Trang trí",
    part: PART,
    description: "Hình con trỏ chuột: pointer, not-allowed, grab...",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Con trỏ BÀN TAY (như khi rê lên link) là giá trị nào?",
        options: ["cursor: hand;", "cursor: pointer;", "cursor: click;", "cursor: link;"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Nút đang bị khóa, muốn con trỏ hình CẤM khi rê vào?",
        options: ["cursor: disabled;", "cursor: not-allowed;", "cursor: block;", "cursor: no;"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Giá trị mặc định của cursor trên chữ thường là gì?",
        options: ["pointer", "auto — trình duyệt tự chọn (chữ hiện con trỏ I-beam)", "default cố định mũi tên", "text-cursor"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao div làm nút bấm (có onclick) nên đặt cursor: pointer?",
        options: [
          "Để div nổi bật hơn",
          "Div không có dấu hiệu 'bấm được' mặc định như button/a — con trỏ tay là tín hiệu thị giác cho người dùng biết đây là vùng tương tác",
          "Bắt buộc của HTML5",
          "Để tăng vùng bấm",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Cặp giá trị nào dành cho phần tử KÉO-THẢ?",
        options: [
          "move không tồn tại",
          "grab (sẵn sàng nắm) và grabbing (đang kéo)",
          "drag và drop",
          "hold và pull",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khi trang đang xử lý (chờ kết quả), giá trị cursor nào thể hiện trạng thái bận?",
        options: ["pointer", "wait hoặc progress (đồng hồ cát / mũi tên kèm vòng xoay)", "busy", "loading"],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có thẻ giả nút class nut-gia. Viết rule .nut-gia đặt  cursor: pointer  và  user-select: none  (chặn bôi đen chữ khi bấm nhanh).",
        requirements: [
          { type: "selector", value: ".nut-gia" },
          { type: "value", selector: ".nut-gia", name: "cursor", value: "pointer" },
          { type: "value", selector: ".nut-gia", name: "user-select", value: "none" },
        ],
        starterCode: "/* HTML căn cứ:\n<div class=\"nut-gia\" role=\"button\" tabindex=\"0\">Xem thêm</div>\n*/\n",
      },
    ],
  },
  {
    name: "list-style",
    topic: "Trang trí",
    part: PART,
    description: "Tùy biến/bỏ dấu đầu dòng của danh sách",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Menu ngang dùng <ul> nhưng còn DẤU CHẤM đầu dòng. Bỏ bằng gì?",
        options: [
          "list-style: none;",
          "bullet: none;",
          "ul-style: off;",
          "Xóa thẻ li",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Đổi dấu đầu dòng thành Ô VUÔNG dùng giá trị nào?",
        options: ["circle", "square", "box", "disc"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Danh sách CÓ SỐ La Mã (i, ii, iii) dùng giá trị nào?",
        options: ["decimal", "lower-roman", "roman-list", "numeric-roman"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Đã đặt list-style: none nhưng menu vẫn THỤT LỀ trái. Vì sao?",
        options: [
          "list-style: none không hoạt động",
          "ul còn padding-left mặc định của trình duyệt — phải xóa thêm (padding: 0)",
          "Phải đặt trên từng li",
          "Do font chữ",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "list-style-position: inside  khác  outside  (mặc định) thế nào?",
        options: [
          "inside ẩn dấu đầu dòng",
          "inside đưa dấu đầu dòng VÀO TRONG khối chữ — dòng thứ hai thẳng hàng với dấu, không thụt theo chữ",
          "inside chỉ cho ol",
          "Không khác gì",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Muốn đầu dòng là EMOJI/ICON tùy ý thay vì chấm tròn, cách hiện đại?",
        options: [
          "Không thể",
          "Dùng list-style: none rồi chèn icon qua ::before (hoặc ::marker với content tùy chỉnh)",
          "Đổi font của ul",
          "list-style: emoji",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có menu ngang dùng ul class menu-ngang. Viết rule .menu-ngang bỏ dấu đầu dòng (list-style: none) và  padding: 0.",
        requirements: [
          { type: "selector", value: ".menu-ngang" },
          { type: "value", selector: ".menu-ngang", name: "list-style", value: "none" },
          { type: "value", selector: ".menu-ngang", name: "padding", value: "0" },
        ],
        starterCode: "/* HTML căn cứ:\n<ul class=\"menu-ngang\">\n  <li><a href=\"/\">Trang chủ</a></li>\n  <li><a href=\"/tin\">Tin tức</a></li>\n</ul>\n*/\n",
      },
    ],
  },
  {
    name: "overflow",
    topic: "Trang trí",
    part: PART,
    description: "Xử lý nội dung tràn hộp: hidden, scroll, auto",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Nội dung dài hơn hộp. Muốn CẮT BỎ phần tràn (không thanh cuộn), dùng gì?",
        options: ["overflow: hidden;", "overflow: cut;", "display: clip;", "max-content: hide;"],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "overflow: auto  hoạt động thế nào?",
        options: [
          "Luôn hiện thanh cuộn",
          "CHỈ hiện thanh cuộn KHI nội dung thật sự tràn",
          "Cắt bỏ phần tràn",
          "Phóng to hộp cho vừa",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Giá trị mặc định của overflow là gì?",
        options: ["hidden", "visible — nội dung tràn vẫn HIỆN đè ra ngoài hộp", "auto", "scroll"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác nhau giữa  overflow: scroll  và  overflow: auto?",
        options: [
          "Như nhau",
          "scroll LUÔN hiện thanh cuộn kể cả khi không tràn (hộp ngắn vẫn có máng cuộn trống); auto chỉ hiện khi cần",
          "auto cuộn nhanh hơn",
          "scroll chỉ cuộn ngang",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khối code dài muốn cuộn NGANG thay vì vỡ dòng — dùng gì?",
        options: [
          "overflow-y: scroll",
          "overflow-x: auto trên khối chứa (pre)",
          "white-space: wrap",
          "width: 200%",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Combo cắt chữ một dòng thành dấu '…' gồm những khai báo nào?",
        options: [
          "text-cut: ellipsis",
          "white-space: nowrap + overflow: hidden + text-overflow: ellipsis",
          "overflow: ellipsis là đủ",
          "font-size: 0",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có khung chat class khung-chat. Viết rule .khung-chat đặt  height: 400px  và  overflow-y: auto  để cuộn dọc khi tin nhắn dài.",
        requirements: [
          { type: "selector", value: ".khung-chat" },
          { type: "value", selector: ".khung-chat", name: "height", value: "400px" },
          { type: "value", selector: ".khung-chat", name: "overflow-y", value: "auto" },
        ],
        starterCode: "/* HTML căn cứ:\n<div class=\"khung-chat\">\n  <p>Tin nhắn 1...</p>\n  <p>Tin nhắn 2...</p>\n</div>\n*/\n",
      },
    ],
  },
  {
    name: "visibility",
    topic: "Trang trí",
    part: PART,
    description: "Ba cách ẩn phần tử: display none, visibility hidden, opacity 0",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "visibility: hidden  làm gì?",
        options: [
          "Xóa phần tử khỏi layout",
          "Ẩn phần tử nhưng VẪN GIỮ CHỖ của nó trong layout",
          "Làm mờ 50%",
          "Thu nhỏ về 0",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "display: none  khác visibility: hidden thế nào?",
        options: [
          "Không khác gì",
          "display: none GỠ phần tử khỏi layout (không chiếm chỗ); visibility: hidden ẩn nhưng chỗ trống vẫn còn",
          "display: none vẫn chiếm chỗ",
          "visibility nhanh hơn",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Hiện lại phần tử đã  visibility: hidden  dùng giá trị nào?",
        options: ["visibility: show;", "visibility: visible;", "visibility: block;", "visibility: on;"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Ba cách ẩn — display:none / visibility:hidden / opacity:0 — khác nhau về TƯƠNG TÁC thế nào?",
        options: [
          "Cả ba đều chặn click",
          "opacity:0 VẪN nhận click; visibility:hidden và display:none thì không",
          "Cả ba đều nhận click",
          "Chỉ display:none nhận click",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Muốn làm hiệu ứng fade (mờ dần rồi biến mất) thì ẩn bằng cách nào?",
        options: [
          "display: none — gọn nhất",
          "opacity (0→1) vì nó chuyển động mượt được bằng transition; display: none thay đổi đột ngột không animate được trực tiếp",
          "visibility vì nó nhanh",
          "Xóa phần tử bằng JS",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Với máy đọc màn hình, phần tử display: none được xử lý thế nào?",
        options: [
          "Vẫn được đọc bình thường",
          "Bị BỎ QUA hoàn toàn — nội dung quan trọng cho screen reader cần kỹ thuật ẩn khác (visually-hidden bằng clip)",
          "Đọc to gấp đôi",
          "Đọc sau cùng",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có quảng cáo class qc-tam. Viết rule .qc-tam ẩn hẳn khỏi layout với  display: none.",
        requirements: [
          { type: "selector", value: ".qc-tam" },
          { type: "value", selector: ".qc-tam", name: "display", value: "none" },
        ],
        starterCode: "/* HTML căn cứ:\n<aside class=\"qc-tam\">Quảng cáo tạm ẩn</aside>\n*/\n",
      },
    ],
  },

  // ===== CHƯƠNG 9: ẢNH & ĐỒ HỌA =====
  {
    name: "object-fit",
    topic: "Ảnh & đồ họa",
    part: PART,
    description: "Cách ảnh <img> lấp đầy khung: cover, contain, fill",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Ảnh <img> bị MÉO khi ép width/height cố định. Thuộc tính nào sửa?",
        options: ["image-render", "object-fit", "background-size", "aspect-fix"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "object-fit: cover  làm ảnh hiển thị thế nào trong khung?",
        options: [
          "Kéo méo cho khít",
          "Giữ tỷ lệ, PHỦ KÍN khung, cắt phần thừa",
          "Hiện trọn ảnh, hở viền",
          "Thu nhỏ một nửa",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Giá trị MẶC ĐỊNH của object-fit (gây méo ảnh) là gì?",
        options: ["cover", "fill — kéo ảnh khít khung bất chấp tỷ lệ", "contain", "none"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Lưới sản phẩm cần mọi ảnh thumbnail ĐỒNG ĐỀU kích thước dù ảnh gốc đủ loại tỷ lệ. Combo chuẩn?",
        options: [
          "Resize tay từng ảnh",
          "Đặt width/height (hoặc aspect-ratio) cố định cho img + object-fit: cover",
          "background-image cho mọi ảnh",
          "transform: scale",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Logo đối tác trong khung cố định KHÔNG ĐƯỢC cắt xén — dùng giá trị nào?",
        options: [
          "cover",
          "contain — hiện trọn logo trong khung, chấp nhận khoảng trống",
          "fill",
          "crop",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "object-position phối hợp với object-fit: cover để làm gì?",
        options: [
          "Xoay ảnh",
          "Chọn PHẦN NÀO của ảnh được giữ lại khi bị cắt (vd object-position: top giữ phần đầu ảnh chân dung)",
          "Đổi tỷ lệ khung",
          "Thêm viền ảnh",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có ảnh thumbnail class anh-thumb. Viết rule .anh-thumb đặt  width: 100%,  height: 200px  và  object-fit: cover.",
        requirements: [
          { type: "selector", value: ".anh-thumb" },
          { type: "value", selector: ".anh-thumb", name: "width", value: "100%" },
          { type: "value", selector: ".anh-thumb", name: "height", value: "200px" },
          { type: "value", selector: ".anh-thumb", name: "object-fit", value: "cover" },
        ],
        starterCode: "/* HTML căn cứ:\n<img class=\"anh-thumb\" src=\"mon-an.jpg\" alt=\"Phở bò\">\n*/\n",
      },
    ],
  },
  {
    name: "aspect-ratio",
    topic: "Ảnh & đồ họa",
    part: PART,
    description: "Khóa tỷ lệ khung hình: 16/9, 1/1...",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Thuộc tính nào KHÓA TỶ LỆ khung (rộng/cao) của phần tử?",
        options: ["ratio", "aspect-ratio", "frame-ratio", "size-ratio"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Khung video chuẩn màn ảnh rộng viết thế nào?",
        options: [
          "aspect-ratio: 16/9;",
          "aspect-ratio: 9-16;",
          "ratio: wide;",
          "video-size: 16x9;",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "aspect-ratio: 1/1  tạo khung hình gì?",
        options: ["Chữ nhật ngang", "VUÔNG — rộng bằng cao", "Tròn", "Tam giác"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Lợi ích chính của aspect-ratio với khung ảnh/video đang tải?",
        options: [
          "Tải ảnh nhanh hơn",
          "Khung GIỮ CHỖ đúng tỷ lệ từ đầu — nội dung tải xong không làm trang 'giật nhảy' layout (CLS)",
          "Tự nén ảnh",
          "Đổi màu khung",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Phần tử có aspect-ratio: 16/9 và width: 320px — chiều cao là bao nhiêu?",
        options: ["320px", "180px — cao = 320 × 9/16", "90px", "Tự do theo nội dung"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Nếu đặt CẢ width lẫn height cố định cùng aspect-ratio thì sao?",
        options: [
          "Trình duyệt báo lỗi",
          "aspect-ratio bị BỎ QUA — nó chỉ tính chiều còn thiếu khi một chiều tự do",
          "aspect-ratio thắng",
          "Phần tử biến mất",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có khung video class khung-video. Viết rule .khung-video đặt  width: 100%  và  aspect-ratio: 16/9.",
        requirements: [
          { type: "selector", value: ".khung-video" },
          { type: "value", selector: ".khung-video", name: "width", value: "100%" },
          { type: "value", selector: ".khung-video", name: "aspect-ratio", value: "16/9" },
        ],
        starterCode: "/* HTML căn cứ:\n<div class=\"khung-video\">\n  <iframe src=\"https://www.youtube.com/embed/abc\"></iframe>\n</div>\n*/\n",
      },
    ],
  },
  {
    name: "filter",
    topic: "Ảnh & đồ họa",
    part: PART,
    description: "Bộ lọc ảnh: blur, grayscale, brightness...",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Làm MỜ NHÒE một ảnh bằng CSS dùng gì?",
        options: ["opacity: 0.5;", "filter: blur(4px);", "image-blur: 4;", "blur: on;"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "filter: grayscale(100%)  làm gì?",
        options: [
          "Tăng tương phản",
          "Biến ảnh thành ĐEN TRẮNG hoàn toàn",
          "Làm tối ảnh",
          "Xóa nền ảnh",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Làm ảnh SÁNG HƠN 20% dùng giá trị nào?",
        options: [
          "filter: brightness(1.2);",
          "filter: light(20);",
          "brightness: +20%;",
          "filter: sun(1.2);",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Có thể GHÉP nhiều filter cùng lúc không?",
        options: [
          "Không, một filter mỗi phần tử",
          "Được — liệt kê cách nhau khoảng trắng: filter: grayscale(50%) brightness(1.1)",
          "Tối đa hai filter",
          "Phải lồng nhiều div",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Logo đối tác muốn ĐEN TRẮNG, hover mới HIỆN MÀU — pattern nào?",
        options: [
          "Hai file ảnh tráo nhau",
          "Mặc định filter: grayscale(100%), khi :hover đổi về grayscale(0) (+ transition cho mượt)",
          "opacity 0 → 1",
          "background-blend",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "backdrop-filter khác filter thế nào?",
        options: [
          "Như nhau",
          "filter áp lên CHÍNH phần tử; backdrop-filter áp lên PHẦN NỀN PHÍA SAU nó — tạo hiệu ứng kính mờ (frosted glass) cho header trong suốt",
          "backdrop-filter chỉ làm tối",
          "filter mạnh hơn",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có logo đối tác class logo-dt. Viết rule .logo-dt đặt  filter: grayscale(100%)  và  opacity: 0.7.",
        requirements: [
          { type: "selector", value: ".logo-dt" },
          { type: "value", selector: ".logo-dt", name: "filter", value: "grayscale(100%)" },
          { type: "value", selector: ".logo-dt", name: "opacity", value: "0.7" },
        ],
        starterCode: "/* HTML căn cứ:\n<img class=\"logo-dt\" src=\"doi-tac.png\" alt=\"Logo đối tác\">\n*/\n",
      },
    ],
  },
  {
    name: "ảnh responsive",
    topic: "Ảnh & đồ họa",
    part: PART,
    description: "max-width: 100% + height: auto — ảnh không phá layout",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Cặp khai báo KINH ĐIỂN cho ảnh co giãn theo khung, không tràn?",
        options: [
          "width: 100vw; height: 100vh;",
          "max-width: 100%; height: auto;",
          "min-width: 100%; height: 100%;",
          "zoom: fit;",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "max-width: 100%  trên ảnh nghĩa là gì?",
        options: [
          "Ảnh luôn rộng đúng 100% khung",
          "Ảnh KHÔNG ĐƯỢC RỘNG QUÁ khung chứa — to thì co lại, nhỏ thì giữ nguyên",
          "Ảnh phóng to gấp đôi",
          "Khung rộng theo ảnh",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Vai trò của  height: auto  đi kèm là gì?",
        options: [
          "Đặt chiều cao bằng khung",
          "Chiều cao tự tính theo TỶ LỆ GỐC khi rộng bị co — ảnh không méo",
          "Ẩn chiều cao",
          "Cao tối đa màn hình",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khác nhau giữa  width: 100%  và  max-width: 100%  trên ảnh nhỏ trong khung to?",
        options: [
          "Như nhau",
          "width: 100% PHÓNG ảnh nhỏ lên kín khung (dễ vỡ hạt); max-width: 100% giữ ảnh nhỏ đúng cỡ thật",
          "max-width phóng to hơn",
          "width: 100% giữ nguyên ảnh",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao vẫn nên ghi thuộc tính width/height TRONG thẻ img dù CSS đã override?",
        options: [
          "Bắt buộc của chuẩn",
          "Trình duyệt dùng cặp số đó tính TỶ LỆ giữ chỗ trước khi ảnh tải — tránh giật layout (CLS); CSS quyết định cỡ hiển thị cuối",
          "Để ảnh tải nhanh hơn",
          "Không cần thiết",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Ảnh trong bài viết hay bị KHOẢNG HỞ vài px dưới đáy do đâu, sửa thế nào?",
        options: [
          "Do file ảnh lỗi",
          "img mặc định là inline, hở do baseline chữ — sửa bằng display: block (hoặc vertical-align: middle)",
          "Do margin của p",
          "Phải dùng background-image",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có ảnh bài viết class anh-bai. Viết rule .anh-bai với  max-width: 100%,  height: auto  và  display: block.",
        requirements: [
          { type: "selector", value: ".anh-bai" },
          { type: "value", selector: ".anh-bai", name: "max-width", value: "100%" },
          { type: "value", selector: ".anh-bai", name: "height", value: "auto" },
          { type: "value", selector: ".anh-bai", name: "display", value: "block" },
        ],
        starterCode: "/* HTML căn cứ:\n<img class=\"anh-bai\" src=\"bien-vung-tau.jpg\" alt=\"Biển Vũng Tàu\" width=\"1200\" height=\"800\">\n*/\n",
      },
    ],
  },
  {
    name: "background shorthand",
    topic: "Ảnh & đồ họa",
    part: PART,
    description: "Gộp các thuộc tính nền vào một dòng background",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "background  là shorthand gộp những gì?",
        options: [
          "Chỉ background-color",
          "color, image, repeat, position, size... — các thuộc tính nền trong MỘT dòng",
          "Cả border và shadow",
          "Mọi thuộc tính của phần tử",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Dòng nào hợp lệ?",
        options: [
          "background: url(nen.jpg) no-repeat center;",
          "background: no-repeat → url(nen.jpg);",
          "background: [nen.jpg, center];",
          "background: image nen.jpg;",
        ],
        correctIndex: 0,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Trong shorthand, background-size viết thế nào?",
        options: [
          "Đứng riêng bất kỳ đâu",
          "SAU position, ngăn bằng dấu gạch chéo: center/cover",
          "Trước url",
          "Không gộp được size",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Bẫy lớn nhất của shorthand background là gì?",
        options: [
          "Viết dài hơn",
          "Nó RESET mọi thuộc tính nền không nhắc tới về mặc định — background: red phía sau sẽ XÓA cả ảnh nền đã khai báo trước đó",
          "Không nhận màu hex",
          "Chỉ chạy trên Chrome",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Trong  background: #333 url(go.png) repeat-x top  — màu #333 đóng vai trò gì?",
        options: [
          "Màu viền",
          "Màu nền DƯỚI ảnh — lộ ra ở vùng ảnh không phủ hoặc khi ảnh chưa/không tải được",
          "Màu chữ",
          "Màu lọc đè lên ảnh",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Khi nào nên viết thuộc tính nền RIÊNG LẺ thay vì shorthand?",
        options: [
          "Luôn dùng shorthand",
          "Khi chỉ muốn ĐỔI MỘT khía cạnh (vd chỉ đổi position khi hover) mà không vô tình reset phần còn lại",
          "Khi nền là màu đơn",
          "Khi file css ngắn",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có khối đầu trang class dau-trang. Viết MỘT dòng shorthand:  background: #0f172a url(sao.png) no-repeat center.",
        requirements: [
          { type: "selector", value: ".dau-trang" },
          {
            type: "value",
            selector: ".dau-trang",
            name: "background",
            value: "#0f172a url(sao.png) no-repeat center",
          },
        ],
        starterCode: "/* HTML căn cứ:\n<header class=\"dau-trang\">\n  <h1>Đêm hội âm nhạc</h1>\n</header>\n*/\n",
      },
    ],
  },
  {
    name: "before after",
    topic: "Ảnh & đồ họa",
    part: PART,
    description: "Pseudo-element ::before/::after — đồ họa trang trí không cần thêm HTML",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "::before và ::after là gì?",
        options: [
          "Hai thẻ HTML mới",
          "Pseudo-element — phần tử ẢO chèn trước/sau NỘI DUNG của phần tử, tạo bằng CSS",
          "Sự kiện chuột",
          "Hai trạng thái hover",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Khai báo nào BẮT BUỘC có thì ::before/::after mới hiển thị?",
        options: ["color", "content (kể cả content: \"\" rỗng)", "width", "display"],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Thêm ký tự » trước mỗi link 'Xem thêm' bằng CSS, viết thế nào?",
        options: [
          '.xem-them::before { content: "» "; }',
          ".xem-them { before: »; }",
          ".xem-them::start { text: »; }",
          "Phải sửa HTML",
        ],
        correctIndex: 0,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Vì sao nội dung QUAN TRỌNG không nên đưa vào content của ::before?",
        options: [
          "Hiển thị chậm",
          "Nó không nằm trong HTML — máy đọc màn hình có thể bỏ qua, không bôi đen copy được, SEO không thấy; chỉ dành cho trang trí",
          "Content giới hạn 10 ký tự",
          "Không hỗ trợ tiếng Việt",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Pattern vẽ ĐƯỜNG KẺ trang trí dưới tiêu đề bằng ::after?",
        options: [
          "content: 'line'",
          'content: ""; display: block; width/height nhỏ + background màu — một hộp ảo làm gạch trang trí',
          "border-bottom của ::after không cần content",
          "text-decoration: underline",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Một phần tử có tối đa bao nhiêu ::before/::after?",
        options: [
          "Không giới hạn",
          "MỘT ::before và MỘT ::after — cần nhiều lớp trang trí hơn thì lồng thêm phần tử",
          "Hai mỗi loại",
          "Tùy trình duyệt",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có tiêu đề class tieu-de-gach. Viết rule cho .tieu-de-gach::after với  content: \"\",  display: block,  width: 48px,  height: 4px  và nền #e34f26.",
        requirements: [
          { type: "selector", value: ".tieu-de-gach::after" },
          { type: "value", selector: ".tieu-de-gach::after", name: "content", value: '""' },
          { type: "value", selector: ".tieu-de-gach::after", name: "display", value: "block" },
          { type: "value", selector: ".tieu-de-gach::after", name: "width", value: "48px" },
          { type: "value", selector: ".tieu-de-gach::after", name: "height", value: "4px" },
          { type: "value", selector: ".tieu-de-gach::after", name: "background-color", value: "#e34f26" },
        ],
        starterCode: "/* HTML căn cứ:\n<h2 class=\"tieu-de-gach\">Dịch vụ của chúng tôi</h2>\n*/\n",
      },
    ],
  },
  {
    name: "img vs background",
    topic: "Ảnh & đồ họa",
    part: PART,
    description: "Khi nào dùng <img>, khi nào dùng background-image",
    questions: [
      {
        tier: 1, type: "MCQ",
        prompt: "Ảnh SẢN PHẨM trong trang bán hàng nên dùng cách nào?",
        options: [
          "background-image cho gọn",
          "Thẻ <img> với alt — ảnh là NỘI DUNG, cần SEO và máy đọc màn hình thấy",
          "::before với content ảnh",
          "Cách nào cũng được",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Họa tiết trang trí lặp phía sau section nên dùng gì?",
        options: [
          "<img> chèn từng cái",
          "background-image — ảnh TRANG TRÍ thuần túy thuộc về CSS",
          "<video>",
          "<canvas>",
        ],
        correctIndex: 1,
      },
      {
        tier: 1, type: "MCQ",
        prompt: "Cách nào cho phép khai báo văn bản thay thế (alt) cho ảnh?",
        options: ["background-image", "Thẻ <img>", "Cả hai", "Không cách nào"],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Tiêu chí phân định NỘI DUNG vs TRANG TRÍ là gì?",
        options: [
          "Ảnh to là nội dung, nhỏ là trang trí",
          "Bỏ ảnh đi mà người đọc MẤT THÔNG TIN → nội dung (dùng img); bỏ đi chỉ kém đẹp → trang trí (dùng background)",
          "PNG là nội dung, JPG là trang trí",
          "Ảnh màu là nội dung",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Về hiệu năng tải, <img> có lợi thế gì so với background-image?",
        options: [
          "Luôn nhẹ hơn",
          "Hỗ trợ loading=\"lazy\", srcset chọn ảnh theo màn hình, trình duyệt ưu tiên tải sớm hơn — background không có các cơ chế đó",
          "Không có khác biệt",
          "background tải trước img",
        ],
        correctIndex: 1,
      },
      {
        tier: 2, type: "MCQ",
        prompt: "Hero banner chữ đè trên ảnh — thực tế hay dùng cách nào, vì sao?",
        options: [
          "Bắt buộc background-image",
          "Cả hai đều gặp: background tiện canh chỉnh; <img> + position absolute thắng về lazy load/srcset — chọn theo việc ảnh có phải nội dung không",
          "Bắt buộc <img>",
          "Không thể đè chữ lên ảnh",
        ],
        correctIndex: 1,
      },
      {
        tier: 3, type: "WRITE_CSS",
        prompt: "HTML có section class hoa-tiet cần họa tiết trang trí. Viết rule .hoa-tiet đặt  background-image: url(cham-bi.svg)  và  background-repeat: repeat.",
        requirements: [
          { type: "selector", value: ".hoa-tiet" },
          { type: "value", selector: ".hoa-tiet", name: "background-image", value: "url(cham-bi.svg)" },
          { type: "value", selector: ".hoa-tiet", name: "background-repeat", value: "repeat" },
        ],
        starterCode: "/* HTML căn cứ:\n<section class=\"hoa-tiet\">\n  <h2>Ưu đãi thành viên</h2>\n</section>\n*/\n",
      },
    ],
  },
];
